# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, StringConstraints


class Contract(RootModel[Any]):
    root: Any = Field(..., title="Contract")


class Address(RootModel[str]):
    root: str = Field(..., max_length=512, min_length=1)
    """
    What a question is about, as the consumer names it: one non-blank line.
    """


class ArtifactRef(BaseModel):
    """
    Evidence too large for a payload: stored by the producing library and
    referenced by id, to be read back through that library.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bytes: int = Field(..., ge=0)
    """
    Size of the stored artifact.
    """
    id: str
    """
    Identifier, unique within the producing library's store.
    """
    kind: str
    """
    What the artifact is — a gate log, a check log, a transcript, a report.
    """


class AuthorConfig(BaseModel):
    """
    One author of a configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    capabilities: list[str]
    """
    The operations the author keeps: a subset of what the layout grants.
    """


class CacheConfig(BaseModel):
    """
    Where a command validator records its passes.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bar_fingerprint: list[str]
    """
    The argv whose output fingerprints the bar: a pass recorded under one
    fingerprint is not a pass under another.
    """
    dir: str
    """
    The directory records are kept in, relative to the working directory
    when relative.
    """


class CodecResponse(BaseModel):
    """
    The response to one frame, in the protocol of the codec served: one JSON object per line.
    """


class Correlation(RootModel[str]):
    root: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    Which question a reply answers: the token the bus minted when it was asked.
    """


class DeliverOptions(BaseModel):
    """
    The options of `deliver`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    address: str
    """
    The spool's address: the directory its receiver bound.
    """
    file: str | None = None
    """
    The file holding the message.
    """
    message: str | None = None
    """
    The message, as JSON text. The verb takes its message from exactly one of
    this, `file`, and stdin, and refuses more than one by name.
    """
    wait: int | None = Field(None, ge=0)
    """
    Seconds to wait for the message to be taken before it is withdrawn.
    """


class Disposition(RootModel[Any]):
    root: Any = Field(..., title="Disposition")
    """
    What the receiver answered the message with: any JSON value, in the vocabulary of the message family the spool carries.
    """


class EnvName(RootModel[str]):
    root: str = Field(..., pattern="^[A-Za-z_][A-Za-z0-9_]{0,127}$")
    """
    The name of an environment variable: ASCII letters, digits and `_`, not starting with a digit.
    """


class FieldPath(RootModel[str]):
    root: str = Field(..., pattern="^[^.]+(\\.[^.]+)*$")
    """
    Object keys joined by `.`: the path to one field of a record.
    """


class InboxCarriedOptions(BaseModel):
    """
    The options of `inbox carried`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["json", "text"] | None = None
    """
    How the list is rendered.
    """
    store: str
    """
    The carry store to list.
    """


class Labels(BaseModel):
    """
    The reserved label keys, plus whatever else a producer stamped.

    Reserved keys are absent rather than empty when unknown, so an enricher can
    tell "not stamped" from "stamped empty". The extras are flattened beside
    them, in the order they were stamped.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    member: str | None = None
    """
    Which member of a conversation produced the event.
    """
    node: str | None = None
    """
    The graph node being executed.
    """
    persona: str | None = None
    """
    The persona that member is running under.
    """
    round: int | None = Field(None, ge=0)
    """
    The round within the run.
    """
    run_id: str | None = None
    """
    The run this event belongs to.
    """
    step: str | None = None
    """
    The step within a node that runs several in sequence.
    """


class Position(RootModel[int]):
    root: int = Field(..., ge=0)
    """
    Where in a queue a record ends: opaque to consumers, and meaningful only to
    the transport that handed it out.

    A consumer receives positions from [`Transport::append`] and
    [`Transport::read`] and hands them back; it never builds one from a number
    it made up. It serializes as its token so a cursor survives a process.
    [`from_token`](Self::from_token) and [`token`](Self::token) exist for a
    transport's own implementation: [`LocalTransport`]'s token is the byte offset
    at a record boundary, [`MemoryTransport`]'s the count of records before it.
    """


class Predicate2(BaseModel):
    """
    The wire shape of a [`Predicate`], before exactly one form is checked.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    all: list[Predicate2] | None = None
    """
    Every one of these holds.
    """
    any: list[Predicate2] | None = None
    """
    At least one of these holds.
    """
    equals: Any | None = None
    """
    The field is there and equals this.
    """
    field: FieldPath | None = None
    """
    The field `equals`, `present` and `non_empty` test.
    """
    non_empty: bool | None = None
    """
    The field holds something (true), or not (false).
    """
    not_: Predicate2 | None = Field(None, alias="not")
    """
    This does not hold.
    """
    present: bool | None = None
    """
    The field is there and not null (true), or not (false).
    """


class QueueStatus(BaseModel):
    """
    Everything a `status` read of one queue reports.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    abandoned: list[Any]
    """
    The records nobody is listening for any more, waiting or pending.
    """
    cursors: dict[str, Position | None]
    """
    Each declared consumer's cursor, `null` for one that has read nothing.
    """
    events: bool
    """
    Whether it keeps an event log.
    """
    pending: Any | None = None
    """
    The record in the pending slot, abandoned or not.
    """
    pending_position: Position | None = None
    """
    Where the pending record was claimed.
    """
    queue: str
    """
    The queue.
    """
    records: int = Field(..., ge=0)
    """
    How many records its log holds.
    """
    unread: int = Field(..., ge=0)
    """
    How many waiting records somebody is still owed a reading of.
    """
    waiting: list[Any]
    """
    The records waiting to be claimed, oldest first: on an event queue every
    waiting record, abandoned ones included; on a plain one the records after
    the default consumer's cursor that a claim hands out.
    """


class ReplyOptions(BaseModel):
    """
    The options of `reply`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration file.
    """
    correlation: Correlation | None = None
    """
    The correlation of the ask the reply answers.
    """
    file: str | None = None
    """
    The reply file; stdin when absent.
    """
    position: Position | None = None
    """
    Where the pending record was claimed, as `next` printed it; absent, the
    ask `correlation` names, or the one pending.
    """
    queue: str
    """
    The queue whose pending ask is answered.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class SchemaId(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    <namespace>.<name>@<version>: which schema a message is.
    """


class SchemaLink(RootModel[str]):
    root: str = Field(..., min_length=1)
    """
    A schema bundle's location — an https:// URL, an http:// URL on a loopback host, a file:// URL, or a path relative to the configuration's directory — and, after a final @, the version pin it is held to: https://example.org/frames.json@8.
    """


class SchemaListOptions(BaseModel):
    """
    The options of `schema list`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    A configuration whose `schemas` links are resolved and registered beside
    the registry; not read from `ONEMESSAGEBUS_CONFIG`.
    """
    format: Literal["json", "text"] | None = None
    """
    How the list is rendered.
    """
    registry: str | None = None
    """
    The registry directory, or the `ONEMESSAGEBUS_REGISTRY` environment
    variable when absent.
    """


class SchemaRegisterOptions(BaseModel):
    """
    The options of `schema register`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    A configuration whose `schemas` links are resolved and registered beside
    the registry; not read from `ONEMESSAGEBUS_CONFIG`.
    """
    file: str
    """
    The file holding the JSON Schema document.
    """
    id: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The id to register under.
    """
    registry: str | None = None
    """
    The registry directory.
    """


class SchemasClearOptions(BaseModel):
    """
    The options of `schemas clear`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["json", "text"] | None = None
    """
    How the count is rendered.
    """


class SchemasCleared(BaseModel):
    """
    The output of `schemas clear`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cache: str
    """
    The cache directory.
    """
    removed: int = Field(..., ge=0)
    """
    How many entries were removed.
    """


class SchemasFetchOptions(BaseModel):
    """
    The options of `schemas fetch`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration whose links are resolved when none is named.
    """
    format: Literal["json", "text"] | None = None
    """
    How the report is rendered.
    """
    links: list[SchemaLink] | None = None
    """
    The links to resolve; every link the configuration names when absent.
    """


class SchemasOptions(BaseModel):
    """
    The options of `schemas`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["json", "text"] | None = None
    """
    How the cache is rendered.
    """


class SendOptions(BaseModel):
    """
    The options of `send`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration file.
    """
    file: str | None = None
    """
    The record file; stdin when absent.
    """
    queue: str
    """
    The queue to append to.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class Sent(BaseModel):
    """
    One record `send` or `reply` appended.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int | None = Field(None, ge=0)
    """
    The id it was given, on a queue that gives one.
    """
    position: int = Field(..., ge=0)
    """
    The position after it.
    """
    queue: str
    """
    The queue it landed on.
    """


class ServeOptions(BaseModel):
    """
    The options of `serve`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    asker: str | None = None
    """
    Who the session listens for.
    """
    codec: str = Field(..., pattern="^[a-z][a-z0-9-]{0,63}$")
    """
    The codec the frames are read with.
    """
    config: str | None = None
    """
    The configuration file.
    """
    file: str | None = None
    """
    A file of frames, one per line; stdin when absent.
    """
    queue: str
    """
    The queue the codec raises and asks on.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    session_seconds: int | None = Field(None, alias="sessionSeconds", ge=1)
    """
    Seconds the session serves before it stops of its own accord.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class StatusOptions(BaseModel):
    """
    The options of `status`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration file.
    """
    format: Literal["json", "text"] | None = None
    """
    How the report is rendered.
    """
    queue: str | None = None
    """
    The queue to report; every declared queue when absent.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class SubscribeOptions(BaseModel):
    """
    The options of `subscribe`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration file.
    """
    format: Literal["json", "text"] | None = None
    """
    How each record is rendered.
    """
    queue: str
    """
    The queue to stream.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    timeout: int | None = Field(None, ge=0)
    """
    Seconds to wait before giving up; no bound when absent.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """
    until: str
    """
    The predicate ending the stream: inline JSON, or a path to a YAML
    document.
    """


class TransportsOptions(BaseModel):
    """
    The options of `transports`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["json", "text"] | None = None
    """
    How the list is rendered.
    """


class ValidateOptions(BaseModel):
    """
    The options of `validate`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    The configuration file.
    """
    file: str | None = None
    """
    The record file; stdin when absent.
    """
    queue: str
    """
    The queue whose validators judge the record.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class ValidatedPass(BaseModel):
    """
    The message may be sent.
    """

    queue: str
    """
    The queue the record was judged for.
    """
    verdict: Literal["pass"]


class ValidatedRefuse(BaseModel):
    """
    The message is refused.
    """

    queue: str
    """
    The queue the record was judged for.
    """
    reason: str
    """
    Why, in the validator's own words.
    """
    verdict: Literal["refuse"]


class ValidatedUnjudged(BaseModel):
    """
    The message could not be judged, so it is not sent either.
    """

    queue: str
    """
    The queue the record was judged for.
    """
    reason: str
    """
    Why no judgement could be made.
    """
    verdict: Literal["unjudged"]


class When1(BaseModel):
    """
    When a validator judges a message: `{carries: <field path>}`, or any queue predicate.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    carries: str = Field(..., pattern="^[^.]+(\\.[^.]+)*$")
    """
    Object keys joined by `.`: the path to one field of a record.
    """


class ArrayOfQueueStatus(RootModel[list[QueueStatus]]):
    root: list[QueueStatus] = Field(..., title="Array_of_QueueStatus")


class AskOptions(BaseModel):
    """
    The options of `ask`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    about: Address | None = None
    """
    What the question is about.
    """
    asker: str | None = None
    """
    Who asks.
    """
    blocking: bool | None = None
    """
    Whether the asker waits on the answer.
    """
    config: str | None = None
    """
    The configuration file.
    """
    correlation: Correlation | None = None
    """
    Listen again for the question this correlation minted, raising nothing.
    """
    file: str | None = None
    """
    The question file; stdin when absent.
    """
    queue: str
    """
    The queue to ask on.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    timeout: int | None = Field(None, ge=0)
    """
    Seconds to wait for the answer; no bound when absent.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class AskedAbandoned(BaseModel):
    """
    The question was abandoned, and nobody re-attended it.
    """

    answer: Literal["abandoned"]
    correlation: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    The question's correlation.
    """


class AskedRefused(BaseModel):
    """
    The bus refused the question, or the reply to it.
    """

    answer: Literal["refused"]
    correlation: Correlation | None = None
    """
    The question's correlation, when the question was asked.
    """
    reason: str
    """
    Why.
    """


class AskedReply(BaseModel):
    """
    A reply record echoing the question's correlation.
    """

    answer: Literal["reply"]
    correlation: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    The question's correlation.
    """
    reply: Any
    """
    The reply record, as the answer queue holds it.
    """


class AskedTimeout(BaseModel):
    """
    The wait elapsed; the question stands.
    """

    answer: Literal["timeout"]
    correlation: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    The question's correlation.
    """


class CachedBundle(BaseModel):
    """
    One entry of the cache, as `schemas` lists it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    confirmed_at: str = Field(
        ..., pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
    )
    """
    When the origin last confirmed it.
    """
    url: str = Field(..., pattern="^[Hh][Tt][Tt][Pp][Ss]?://")
    """
    The link's location, without its pin.
    """
    version: str = Field(..., pattern="^[0-9]+(\\.[0-9]+){0,2}$")
    """
    The version the cached bundle declares.
    """


class CarriedEntry(BaseModel):
    """
    One carried message, as the store holds it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    message: Any
    """
    The message.
    """
    schema_: str = Field(
        ...,
        alias="schema",
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The schema the message is.
    """
    ts: str
    """
    When it was carried: RFC 3339, millisecond precision, UTC.
    """


class ClaimedRecord(BaseModel):
    """
    The record `next` claimed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int | None = Field(None, ge=0)
    """
    The record's id, on a queue that gives one.
    """
    position: int = Field(..., ge=0)
    """
    Where the claim was recorded: what `reply` names the record by.
    """
    queue: str
    """
    The queue it was claimed from.
    """
    record: Any
    """
    The record.
    """


class Envelope(BaseModel):
    """
    One event, as a producing process writes it and as a consumer reads it.

    Merge order across streams is `(ts, stream, seq)`. A consumer detects loss
    as a per-stream [`seq`](Self::seq) gap; there is no cross-stream promise
    beyond the timestamps.

    The type parameter is the [`Vocabulary`] the envelope is written over: it
    decides the source words, the dimensions carried between `kind` and
    `labels`, and the label set. Deserialization refuses an unknown top-level
    field, a `seq` that is not an unsigned integer, a source word the vocabulary
    does not admit, and a missing required field — each by name.
    """

    artifacts: list[ArtifactRef] | None = Field([], validate_default=True)
    """
    Evidence stored by the producing library and referenced by id.
    """
    kind: str
    """
    What happened, as its producer named it.
    """
    labels: Labels | None = Field({}, validate_default=True)
    """
    The reserved keys the vocabulary declares plus free-form extras.
    Producers stamp what they know; enrichers never rewrite.
    """
    payload: dict[str, Any] | None = {}
    """
    Kind-specific detail. Text fields are bounded by
    [`MAX_PAYLOAD_TEXT_BYTES`](crate::MAX_PAYLOAD_TEXT_BYTES); larger
    evidence is an [`ArtifactRef`].
    """
    phase: Literal["development", "integrate", "review", "release"] | None = None
    """
    Which part of a change's life the event belongs to, as its producer
    classified it.
    """
    seq: int = Field(..., ge=0)
    """
    Monotonic per [`stream`](Self::stream).
    """
    source: Literal["agentgraph", "vcs", "pipeline"]
    """
    What produced the event, in the vocabulary's words.
    """
    stream: str
    """
    Unique id of the producing process.
    """
    ts: str
    """
    RFC 3339, millisecond precision, UTC.
    """
    v: int = Field(..., ge=0)
    """
    The envelope schema version the producer wrote against.
    """


class EventsEmitOptions(BaseModel):
    """
    The options of `events emit`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    file: str | None = None
    """
    The payload file; stdin when absent.
    """
    format: Literal["json", "text"] | None = None
    """
    How the written envelope is rendered.
    """
    kind: str
    """
    The kind of the event.
    """
    labels: dict[str, str] | None = None
    """
    Labels to stamp, by key.
    """
    path: str
    """
    The stream file to append to.
    """
    profile: str | None = None
    """
    The profile whose vocabulary the envelope is written over.
    """
    source: str | None = None
    """
    The source word; the profile's default when absent.
    """
    stream: str
    """
    The stream id to stamp.
    """


class EventsMergeOptions(BaseModel):
    """
    The options of `events merge`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    files: list[str]
    """
    The stream files to merge.
    """
    filter: str | None = None
    """
    A filter spec: inline JSON, or a path to a YAML document.
    """
    format: Literal["json", "text"] | None = None
    """
    How the merged stream is rendered.
    """
    profile: str | None = None
    """
    The profile whose vocabulary the streams are read through.
    """


class FetchedLinkConfirmed(BaseModel):
    """
    The cached entry, confirmed current by the origin.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    link: str = Field(..., min_length=1)
    """
    The link, as named.
    """
    outcome: Literal["confirmed"]
    version: str = Field(..., pattern="^[0-9]+(\\.[0-9]+){0,2}$")
    """
    The version the cached bundle declares.
    """


class FetchedLinkFailed(BaseModel):
    """
    Not resolved.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    link: str = Field(..., min_length=1)
    """
    The link, as named.
    """
    outcome: Literal["failed"]
    reason: str
    """
    Why not.
    """


class FetchedLinkFetched(BaseModel):
    """
    Fetched from the origin, and stored when the link is pinned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    link: str = Field(..., min_length=1)
    """
    The link, as named.
    """
    outcome: Literal["fetched"]
    version: str = Field(..., pattern="^[0-9]+(\\.[0-9]+){0,2}$")
    """
    The version the bundle declares.
    """


class FetchedLinkRead(BaseModel):
    """
    A `file://` or bare-path bundle, read.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    link: str = Field(..., min_length=1)
    """
    The link, as named.
    """
    outcome: Literal["read"]
    version: str = Field(..., pattern="^[0-9]+(\\.[0-9]+){0,2}$")
    """
    The version the bundle declares.
    """


class FetchedLinkReused(BaseModel):
    """
    The cached entry, reused because its revalidation could not be made.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    link: str = Field(..., min_length=1)
    """
    The link, as named.
    """
    outcome: Literal["reused"]
    reason: str
    """
    Why the revalidation failed.
    """
    version: str = Field(..., pattern="^[0-9]+(\\.[0-9]+){0,2}$")
    """
    The version the cached bundle declares.
    """


class FieldEquals(BaseModel):
    """
    Equality against one frame field.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    equals: Any
    """
    A JSON scalar. SDKs intentionally expose this as their arbitrary-JSON
    type because its runtime type participates in equality.
    """
    field: FieldPath
    """
    Dot-separated object keys.
    """


class KindEntry(BaseModel):
    """
    One kind a build can open.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str
    """
    The kind.
    """
    origin: Literal["builtin", "registered", "plugin"]
    """
    Where it comes from.
    """
    path: str | None = None
    """
    The plugin executable, for a kind a plugin serves.
    """


class LogRecord(BaseModel):
    """
    One line of a queue's log, as `subscribe` streams it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    position: int = Field(..., ge=0)
    """
    The position after it.
    """
    record: Any
    """
    The line: on an event queue, `{"event": ..., ...record}`.
    """


class Matcher(BaseModel):
    """
    One matcher: every field it names must hold of an envelope, and a field it
    does not name is not consulted.
    """

    kind: str | None = None
    """
    A glob over the kind's kebab-case wire string, where `*` stands for any
    run of characters including none and every other character is itself.
    """
    member: str | None = None
    """
    The `member` label.
    """
    node: str | None = None
    """
    The `node` label.
    """
    persona: str | None = None
    """
    The `persona` label.
    """
    phase: Literal["development", "integrate", "review", "release"] | None = None
    """
    The phase the envelope was stamped at.
    """
    run_id: str | None = None
    """
    The `run_id` label.
    """
    source: Literal["agentgraph", "vcs", "pipeline"] | None = None
    """
    The producer, by exact equality.
    """
    step: str | None = None
    """
    The `step` label.
    """


class NextOptions(BaseModel):
    """
    The options of `next`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    asker: str | None = None
    """
    The asker this claim listens for, taking back what it abandoned.
    """
    config: str | None = None
    """
    The configuration file.
    """
    consumer: str | None = None
    """
    Who claims; the default consumer when absent.
    """
    format: Literal["json", "text"] | None = None
    """
    How the claimed record is rendered.
    """
    queue: str
    """
    The queue to claim from.
    """
    registry: str | None = None
    """
    The registry directory whose schemas are registered beside the layout's.
    """
    transport_dir: str | None = Field(None, alias="transportDir")
    """
    The transport directory.
    """


class Predicate(BaseModel):
    """
    The wire shape of a [`Predicate`], before exactly one form is checked.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    all: list[Predicate2] | None = None
    """
    Every one of these holds.
    """
    any: list[Predicate2] | None = None
    """
    At least one of these holds.
    """
    equals: Any | None = None
    """
    The field is there and equals this.
    """
    field: FieldPath | None = None
    """
    The field `equals`, `present` and `non_empty` test.
    """
    non_empty: bool | None = None
    """
    The field holds something (true), or not (false).
    """
    not_: Predicate2 | None = Field(None, alias="not")
    """
    This does not hold.
    """
    present: bool | None = None
    """
    The field is there and not null (true), or not (false).
    """


class RegistryDocument(BaseModel):
    """
    One file of a `--registry` directory: a document and the id it is under.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The id the document is registered under.
    """
    schema_: Any = Field(..., alias="schema")
    """
    The JSON Schema document.
    """


class Replied(BaseModel):
    """
    What `reply` did: the pending record it answered, and the records it
    appended — a reply routed by its halves appends more than one, and one with
    no verdict answers nothing.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    answered: ClaimedRecord | None = None
    """
    The pending record answered, or `null` when the reply carried nothing
    for its answer queue.
    """
    correlation: Correlation | None = None
    """
    The correlation of the ask the reply bound to, when it carries one.
    """
    sent: list[Sent]
    """
    Every record appended, in order.
    """


class SchemaCache(BaseModel):
    """
    The output of `schemas`: the cache directory and every entry it holds.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cache: str
    """
    The cache directory.
    """
    entries: list[CachedBundle]
    """
    One entry per cached location and declared version, by location then
    version.
    """


class SchemaCheckOptions(BaseModel):
    """
    The options of `schema check`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    A configuration whose `schemas` links are resolved and registered beside
    the registry; not read from `ONEMESSAGEBUS_CONFIG`.
    """
    file: str | None = None
    """
    The payload file; stdin when absent.
    """
    id: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The id to check against.
    """
    registry: str | None = None
    """
    The registry directory.
    """


class SchemaEntry(BaseModel):
    """
    One entry of `schema list`.

    `family` and `version` restate `id` for a reader that does not parse ids, so
    an entry whose restatement contradicts its id is refused on read rather than
    handed back with two answers to the same question.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    family: str
    """
    The id without its version.
    """
    id: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The full id.
    """
    version: int = Field(..., ge=0)
    """
    The version.
    """


class SchemaGenOptions(BaseModel):
    """
    The options of `schema gen`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    """
    A configuration whose `schemas` links are resolved and registered beside
    the registry; not read from `ONEMESSAGEBUS_CONFIG`.
    """
    id: str = Field(
        ...,
        pattern="^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[1-9][0-9]*$",
        title="SchemaId",
    )
    """
    The id to render.
    """
    lang: Literal["json", "rust", "python", "typescript"]
    """
    The language to render it for.
    """
    registry: str | None = None
    """
    The registry directory.
    """


class Supersede(BaseModel):
    """
    A newer record replacing a waiting older one.

    When a record that `when` admits is queued (any record, where `when` is
    absent), every waiting record whose `key` field equals the new record's is
    removed from waiting. Only waiting records are replaced: a record already
    claimed is not.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    key: str = Field(..., pattern="^[^.]+(\\.[^.]+)*$")
    """
    The field whose equal values replace one another.
    """
    when: Predicate | None = None
    """
    Which records supersede at all.
    """


class TransportConfig(BaseModel):
    """
    The `transport` block of a configuration: the kind, the directory a
    directory-backed transport keeps its queues in, and whatever else the kind
    takes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dir: str | None = None
    """
    The directory a directory-backed transport keeps its queues in.
    """
    kind: str
    """
    The kind: `local`, `memory`, or a kind registered in-process or served
    by a plugin.
    """


class Validated(RootModel[ValidatedPass | ValidatedRefuse | ValidatedUnjudged]):
    root: ValidatedPass | ValidatedRefuse | ValidatedUnjudged = Field(..., title="Validated")
    """
    What `validate` judged: the queue, and the verdict its validators reached.
    """


class ArrayOfKindEntry(RootModel[list[KindEntry]]):
    root: list[KindEntry] = Field(..., title="Array_of_KindEntry")


class ArrayOfSchemaEntry(RootModel[list[SchemaEntry]]):
    root: list[SchemaEntry] = Field(..., title="Array_of_SchemaEntry")


class Asked(RootModel[AskedReply | AskedTimeout | AskedAbandoned | AskedRefused]):
    root: AskedReply | AskedTimeout | AskedAbandoned | AskedRefused = Field(..., title="Asked")
    """
    What `ask` answered. Every answer names itself in `answer`, and only a
    reply carries a `reply`: a caller reading the reply member of a timeout, an
    abandoned listener or a refusal reads nothing.
    """


class BindingAnswer(BaseModel):
    """
    Write a response and do nothing on the bus.
    """

    do: Literal["answer"]
    response: Any
    """
    The frame response as arbitrary JSON, preserving template value types.
    """
    when: FieldEquals | None = None
    """
    The condition; absent means this binding always holds.
    """


class BindingAsk(BaseModel):
    """
    Ask a question and relay its ruling.
    """

    blocking: bool | None = False
    """
    Whether the question blocks its queue.
    """
    do: Literal["ask"]
    record: Any
    """
    The question asked on the served queue as arbitrary JSON.
    """
    response: Any
    """
    The arbitrary-JSON response resolved from a ruling.
    """
    unanswered: Any
    """
    The arbitrary-JSON response used when no ruling can be resolved.
    """
    when: FieldEquals | None = None
    """
    The condition; absent means this binding always holds.
    """


class BindingRaise(BaseModel):
    """
    Raise a record, then respond or fail.
    """

    do: Literal["raise"]
    fail: str | None = None
    """
    The failure written after raising.
    """
    record: Any
    """
    The record raised on the served queue as arbitrary JSON.
    """
    response: Any | None = None
    """
    The response written after raising as arbitrary JSON.
    """
    when: FieldEquals | None = None
    """
    The condition; absent means this binding always holds.
    """


class BindingRefuse(BaseModel):
    """
    Refuse the frame and write nothing.
    """

    do: Literal["refuse"]
    message: str
    """
    The refusal written on stderr.
    """
    when: FieldEquals | None = None
    """
    The condition; absent means this binding always holds.
    """


class Filter(BaseModel):
    """
    Which envelopes pass.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    exclude: list[Matcher] | None = None
    """
    Matchers that reject. A match here rejects whatever
    [`include`](Self::include) said, so a broad include beside a narrow
    exclude is how "all of this except that" is written.
    """
    include: list[Matcher] | None = None
    """
    Matchers an envelope satisfies one of to pass. Absent or empty admits
    every envelope, so a filter that only rejects need name nothing here.
    """


class PolicyConfig(BaseModel):
    """
    The policy keys a configuration sets on a queue.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    blocking_first: bool | None = None
    """
    See [`Policy::blocking_first`].
    """
    delivery: Literal["at-least-once"] | None = None
    """
    See [`Policy::delivery`].
    """
    hold_pending: bool | None = None
    """
    See [`Policy::hold_pending`].
    """
    ordering: Literal["per-queue"] | None = None
    """
    See [`Policy::ordering`].
    """
    projection: str | None = None
    """
    See [`Policy::projection`].
    """
    retention: Literal["keep"] | None = None
    """
    See [`Policy::retention`].
    """
    supersede_on: Supersede | None = None
    """
    See [`Policy::supersede_on`].
    """


class QueueConfig(BaseModel):
    """
    One queue of a configuration: an addition, or an override of a layout's
    queue. Every key left out keeps the layout's value — or, for an addition,
    the plain default.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    answers: str | None = None
    """
    The queue a reply to a pending record is appended to.
    """
    claims: Predicate | None = None
    """
    Which records a claim hands out.
    """
    consumers: list[str] | None = None
    """
    The consumers whose cursors `status` reports.
    """
    numbered: bool | None = None
    """
    Whether a push numbers each record.
    """
    policy: PolicyConfig | None = None
    """
    The policy's keys to set.
    """
    schema_: SchemaId | None = Field(None, alias="schema")
    """
    The schema records are validated against.
    """


class SchemasFetched(BaseModel):
    """
    The output of `schemas fetch`: one report per link, in the order named.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    links: list[
        FetchedLinkRead
        | FetchedLinkFetched
        | FetchedLinkConfirmed
        | FetchedLinkReused
        | FetchedLinkFailed
    ]
    """
    Each link and how it ended.
    """


class ValidatorConfig(BaseModel):
    """
    One validator of a configuration: the external kind, which a Rust
    validator a linking consumer registers is not — that one is code
    ([`Bus::with_validator`]).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cache: CacheConfig | None = None
    """
    Where its passes are recorded; nowhere when absent.
    """
    command: list[str]
    """
    The command's argv, the program first: the message on its stdin, exit 0
    a pass, 1 a refusal with its stderr as the reason, anything else
    unjudged.
    """
    kind: Literal["command"]
    """
    Which kind of validator it is.
    """
    on: str
    """
    The queue whose offered messages it judges.
    """
    when: When1 | Predicate | None = None
    """
    Which of them it judges; every one when absent.
    """


class FrameConfig(BaseModel):
    """
    One selected frame in a configured codec.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bindings: list[BindingAnswer | BindingRefuse | BindingRaise | BindingAsk]
    """
    Actions tried in order; the first whose condition holds is applied.
    """
    schema_: SchemaId = Field(..., alias="schema")
    """
    The registered schema that validates this frame.
    """


class CodecConfig(BaseModel):
    """
    What a host configures for one codec, under its name in the configuration's
    `codecs` block.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    about_env: EnvName | None = None
    """
    The variable what the member's questions are about is read from.
    """
    asker_env: EnvName | None = None
    """
    The variable the asker is read from, when `--asker` is not given.
    """
    frames: dict[str, FrameConfig]
    """
    The protocol's entries, keyed by the selected field's value.
    """
    queue: str | None = None
    """
    The queue the codec raises and asks on; `serve <queue>` must name the
    same one.
    """
    reply_window_seconds: int | None = Field(None, ge=1)
    """
    Whole seconds a question the codec asks waits for its ruling before the
    codec answers without one.
    """
    select: FieldPath
    """
    The frame field whose string value selects an entry in [`Self::frames`].
    """
    session_env: EnvName | None = None
    """
    The variable the session bound is read from, in whole seconds, when
    `--session-seconds` is not given.
    """


class Config(BaseModel):
    """
    What a configuration file says, read and checked on its own.

    It opens no queue and authors no record: [`resolve`](Self::resolve) binds it
    to the layouts and transports a process has, and answers the [`Bus`] that
    does.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    authors: dict[str, AuthorConfig] | None = None
    """
    Authors whose grants the configuration narrows. It may never widen them.
    """
    codecs: (
        dict[Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9-]{0,63}$")], CodecConfig]
        | None
    ) = None
    """
    What a host configures for each codec `serve` runs, by the codec's name.
    Which names there are is the binary's: one no linked codec answers to is
    refused where `serve` resolves it.
    """
    profile: str | None = None
    """
    A layout a linked profile declares, by name: its queues, policies,
    authors, operations and schemas.
    """
    queues: dict[str, QueueConfig] | None = None
    """
    Queues added to the layout's, or overriding one of the layout's by name.
    """
    schemas: list[SchemaLink] | None = None
    """
    Schema bundles another program publishes, each linked by a URL or path
    and pinned to a version (`docs/schema-links.md`). [`load`](Self::load)
    parses each link and resolves nothing; [`resolve_links`](Self::resolve_links)
    is the call that does.
    """
    transport: TransportConfig
    """
    The transport the queues are kept on.
    """
    validators: list[ValidatorConfig] | None = None
    """
    Validators judging what is offered to a queue before anything is
    appended, in the order each queue judges by them.
    """
    version: int = Field(..., ge=0)
    """
    Always [`CONFIG_VERSION`].
    """


Predicate2.model_rebuild()
