# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""Open domain names shared by the generated configuration and messages."""

from typing import TypeAlias

Author: TypeAlias = str
"""An open author name; which names may write is resolved from configuration."""

Operation: TypeAlias = str
"""An operation name from the selected layout's runtime vocabulary."""
