# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""Every registered message's model, by its family's name."""

from .messages import (
    agent_artifact_ref_v1,
    agent_command_outcome_v1,
    agent_event_envelope_v1,
    agent_event_envelope_v2,
    agent_event_filter_v1,
    agent_labels_v1,
    agent_note_v1,
    agent_onejudge_frame_assess_v6,
    agent_onejudge_frame_judge_v6,
    agent_onejudge_frame_respond_v6,
    agent_onejudge_frame_supervisor_v6,
    agent_onejudge_frame_user_v6,
    agent_planner_surface_v1,
    agent_queued_commands_v1,
    agent_queued_reply_v1,
    agent_reply_envelope_v2,
    agent_reply_envelope_v3,
    bus_resident_protocol_v1,
    onemessagebus_transport_hello_v1,
    onemessagebus_transport_reply_v1,
    onemessagebus_transport_request_v1,
)

ArtifactRefV1 = agent_artifact_ref_v1.ArtifactRef
ArtifactRef = ArtifactRefV1
CommandOutcomeV1 = agent_command_outcome_v1.CommandOutcome
CommandOutcome = CommandOutcomeV1
EventEnvelopeV1 = agent_event_envelope_v1.Envelope
EventEnvelopeV2 = agent_event_envelope_v2.Envelope
EventEnvelope = EventEnvelopeV2
EventFilterV1 = agent_event_filter_v1.Filter
EventFilter = EventFilterV1
LabelsV1 = agent_labels_v1.Labels
Labels = LabelsV1
NoteV1 = agent_note_v1.Note
Note = NoteV1
OnejudgeFrameAssessV6 = agent_onejudge_frame_assess_v6.AssessFrame
OnejudgeFrameAssess = OnejudgeFrameAssessV6
OnejudgeFrameJudgeV6 = agent_onejudge_frame_judge_v6.JudgeFrame
OnejudgeFrameJudge = OnejudgeFrameJudgeV6
OnejudgeFrameRespondV6 = agent_onejudge_frame_respond_v6.RespondFrame
OnejudgeFrameRespond = OnejudgeFrameRespondV6
OnejudgeFrameSupervisorV6 = agent_onejudge_frame_supervisor_v6.SupervisorFrame
OnejudgeFrameSupervisor = OnejudgeFrameSupervisorV6
OnejudgeFrameUserV6 = agent_onejudge_frame_user_v6.UserFrame
OnejudgeFrameUser = OnejudgeFrameUserV6
PlannerSurfaceV1 = agent_planner_surface_v1.Surface
PlannerSurface = PlannerSurfaceV1
QueuedCommandsV1 = agent_queued_commands_v1.QueuedCommands
QueuedCommands = QueuedCommandsV1
QueuedReplyV1 = agent_queued_reply_v1.QueuedReply
QueuedReply = QueuedReplyV1
ReplyEnvelopeV2 = agent_reply_envelope_v2.ReplyEnvelope
ReplyEnvelopeV3 = agent_reply_envelope_v3.ReplyEnvelope
ReplyEnvelope = ReplyEnvelopeV3
ResidentProtocolV1 = bus_resident_protocol_v1.ResidentLine
ResidentProtocol = ResidentProtocolV1
TransportHelloV1 = onemessagebus_transport_hello_v1.PluginHello
TransportHello = TransportHelloV1
TransportReplyV1 = onemessagebus_transport_reply_v1.PluginReply
TransportReply = TransportReplyV1
TransportRequestV1 = onemessagebus_transport_request_v1.PluginRequest
TransportRequest = TransportRequestV1

__all__ = [
    "ArtifactRef",
    "ArtifactRefV1",
    "CommandOutcome",
    "CommandOutcomeV1",
    "EventEnvelope",
    "EventEnvelopeV1",
    "EventEnvelopeV2",
    "EventFilter",
    "EventFilterV1",
    "Labels",
    "LabelsV1",
    "Note",
    "NoteV1",
    "OnejudgeFrameAssess",
    "OnejudgeFrameAssessV6",
    "OnejudgeFrameJudge",
    "OnejudgeFrameJudgeV6",
    "OnejudgeFrameRespond",
    "OnejudgeFrameRespondV6",
    "OnejudgeFrameSupervisor",
    "OnejudgeFrameSupervisorV6",
    "OnejudgeFrameUser",
    "OnejudgeFrameUserV6",
    "PlannerSurface",
    "PlannerSurfaceV1",
    "QueuedCommands",
    "QueuedCommandsV1",
    "QueuedReply",
    "QueuedReplyV1",
    "ReplyEnvelope",
    "ReplyEnvelopeV2",
    "ReplyEnvelopeV3",
    "ResidentProtocol",
    "ResidentProtocolV1",
    "TransportHello",
    "TransportHelloV1",
    "TransportReply",
    "TransportReplyV1",
    "TransportRequest",
    "TransportRequestV1",
]
