#!/usr/bin/env node
// Writes src/generated/ from the Rust-owned schema bundle: TypeScript types and
// Zod schemas for every output root, every option root and every registered
// message, and the capability manifest the client builds argv and resident
// requests from. Nothing here restates a wire shape; it reads them.
//
// Usage: node scripts/generate.mjs [--check] [--out DIR]
//   --check  write nothing; exit 1 naming each file that differs from a fresh
//            generation (or is missing, or is no longer generated).
//   --out    the directory to write or check; src/generated by default.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
// Not published (`files` is dist + README), so reaching the repository's shared
// bundle reader is safe: this script only ever runs from a checkout.
import { schemaBundle } from "../../../scripts/sdk-bundle.mjs";
import { typescriptDeclarations } from "./typescript-generator.mjs";
import { RUNTIME_MODULE, UnsupportedSchema, zodDeclarations } from "./zod-generator.mjs";

const PACKAGE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const RERUN = "just sdk-generate";

function argument(name) {
  const at = process.argv.indexOf(name);
  return at === -1 ? undefined : process.argv[at + 1];
}

const check = process.argv.includes("--check");
const out = resolve(argument("--out") ?? join(PACKAGE, "src/generated"));

const BANNER =
  "// Generated by scripts/generate.mjs from the onemessagebus schema bundle. Do not edit; run `just sdk-generate`.";

/** Bundle keys that are not JSON Schema documents. */
const NOT_ROOTS = new Set(["capabilities", "vocabulary", "options", "messages"]);

const pascal = (text) =>
  text
    .split(/[^A-Za-z0-9]+/u)
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join("");

/** `agent.planner-surface@1` → `AgentPlannerSurfaceV1`. */
const messageType = (id) => {
  const [family, version] = id.split("@");
  return `${pascal(family)}V${version}`;
};
const kebab = (text) => text.replace(/[^A-Za-z0-9]+/gu, "-").toLowerCase();

async function documentModule(document, typeName, at, imports = "") {
  const types = await typescriptDeclarations(document, typeName);
  const zod = zodDeclarations(document, { exportName: `${typeName}Schema`, typeName, at });
  return `${BANNER}\nimport { z } from "zod";\nimport { anyOf, contract, oneOf } from "../runtime.js";\n${imports}\n${types}\n\n${zod}\n`;
}

async function generate(bundle) {
  /** @type {Map<string, string>} */
  const files = new Map();
  const roots = Object.keys(bundle).filter((key) => !NOT_ROOTS.has(key));
  const optionRoots = Object.keys(bundle.options);

  // The manifest says which roots must exist; a capability naming one the bundle
  // lacks is a broken contract, not a missing type to paper over.
  for (const capability of bundle.capabilities) {
    if (capability.options !== null && !(capability.options in bundle.options)) {
      throw new Error(
        `capability ${capability.method} names option root ${capability.options}, which the bundle does not carry; register that root in sdk_schema::bundle() or correct the capability in crates/onemessagebus/src/capability.rs, then rerun \`${RERUN}\``,
      );
    }
    if (capability.output !== null && !roots.includes(capability.output)) {
      throw new Error(
        `capability ${capability.method} names output root ${capability.output}, which the bundle does not carry; register that root in sdk_schema::bundle() or correct the capability in crates/onemessagebus/src/capability.rs, then rerun \`${RERUN}\``,
      );
    }
  }

  files.set("runtime.ts", `${BANNER}\n${RUNTIME_MODULE}`);
  for (const key of roots) {
    files.set(`roots/${kebab(key)}.ts`, await documentModule(bundle[key], pascal(key), key));
  }
  for (const key of optionRoots) {
    files.set(
      `options/${kebab(key)}.ts`,
      await documentModule(bundle.options[key], pascal(key), `options/${key}`),
    );
  }
  const messageIds = Object.keys(bundle.messages).sort();
  for (const id of messageIds) {
    const typeName = messageType(id);
    const module = await documentModule(
      bundle.messages[id],
      typeName,
      `messages/${id}`,
      'import { registeredMessage } from "../../message.js";\n',
    );
    const document = JSON.stringify(bundle.messages[id]);
    files.set(
      `messages/${kebab(id)}.ts`,
      `${module}\n/** \`${id}\`, as the Rust registry holds it. */\nexport const ${typeName} = registeredMessage(${JSON.stringify(id)}, ${typeName}Schema, ${document});\n`,
    );
  }

  const capabilities = Object.fromEntries(bundle.capabilities.map((c) => [c.method, c]));
  const methods = bundle.capabilities.map((c) => c.method);
  const optionType = (c) => pascal(c.options);
  const outputType = (c) => (c.output === null ? "string" : pascal(c.output));
  const rootImports = [...new Set(bundle.capabilities.map((c) => c.output).filter(Boolean))]
    .sort()
    .map(
      (key) =>
        `import { type ${pascal(key)}, ${pascal(key)}Schema } from "./roots/${kebab(key)}.js";`,
    );
  const optionImports = [...new Set(bundle.capabilities.map((c) => c.options).filter(Boolean))]
    .sort()
    .map(
      (key) =>
        `import { type ${pascal(key)}, ${pascal(key)}Schema } from "./options/${kebab(key)}.js";`,
    );
  files.set(
    "capabilities.ts",
    `${BANNER}
import type { z } from "zod";
${optionImports.join("\n")}
${rootImports.join("\n")}

/** How one option reaches the command line. */
export type FlagKind = "positional" | "value" | "repeated" | "switch" | "key-value";

/** One option and the flag it renders to; \`flag\` is empty for a positional. */
export interface OptionBinding {
  readonly option: string;
  readonly flag: string;
  readonly kind: FlagKind;
}

/** How a verb's stdout reaches a caller. */
export type StdoutShape = "json" | "jsonl" | "text";

/** One thing the binary can do, as \`onemessagebus::CAPABILITIES\` declares it. */
export interface Capability {
  readonly method: string;
  readonly verb: readonly string[];
  readonly options: string | null;
  readonly output: string | null;
  readonly stdout: StdoutShape;
  readonly stdin: boolean;
  readonly library_entry: string;
  readonly bindings: readonly OptionBinding[];
  readonly uncovered: readonly { readonly flag: string; readonly reason: string }[];
}

export const CAPABILITIES = ${JSON.stringify(capabilities, null, 2)} as const satisfies Record<string, Capability>;

export type CapabilityMethod = keyof typeof CAPABILITIES;

/** Each capability's options, as its options root declares them. */
export interface CapabilityOptions {
${bundle.capabilities.map((c) => `  ${c.method}: ${optionType(c)};`).join("\n")}
}

/** What one document (or one line, for a \`jsonl\` verb) of each capability's stdout is. */
export interface CapabilityOutputs {
${bundle.capabilities.map((c) => `  ${c.method}: ${outputType(c)};`).join("\n")}
}

/** The schema each capability's options are validated by before a call. */
export const OPTION_SCHEMAS: { [M in CapabilityMethod]: z.ZodType<CapabilityOptions[M]> } = {
${bundle.capabilities.map((c) => `  ${c.method}: ${optionType(c)}Schema,`).join("\n")}
};

/** The schema one document (or one line) of each capability's stdout is parsed by; \`null\` for text. */
export const OUTPUT_SCHEMAS: { [M in CapabilityMethod]: z.ZodType<CapabilityOutputs[M]> | null } = {
${bundle.capabilities.map((c) => `  ${c.method}: ${c.output === null ? "null" : `${pascal(c.output)}Schema`},`).join("\n")}
};

export const METHODS = ${JSON.stringify(methods)} as const;
`,
  );

  // Each document's `$defs` are its own, and two documents may name different
  // shapes alike (`Phase`, `Labels`), so a barrel exports each module's root and
  // nothing it happens to declare on the way.
  const rootExport = (path, name) =>
    `export type { ${name} } from "${path}";\nexport { ${name}Schema } from "${path}";`;
  files.set(
    "messages/index.ts",
    `${BANNER}
${messageIds.map((id) => `import { ${messageType(id)} } from "./${kebab(id)}.js";`).join("\n")}

${messageIds.map((id) => `export { ${messageType(id)}, ${messageType(id)}Schema } from "./${kebab(id)}.js";`).join("\n")}

/** Every message the Rust registry holds, by id. */
export const MESSAGES = {
${messageIds.map((id) => `  ${JSON.stringify(id)}: ${messageType(id)},`).join("\n")}
} as const;
`,
  );

  files.set(
    "index.ts",
    `${BANNER}
${roots.map((key) => rootExport(`./roots/${kebab(key)}.js`, pascal(key))).join("\n")}
${optionRoots.map((key) => rootExport(`./options/${kebab(key)}.js`, pascal(key))).join("\n")}
export * from "./capabilities.js";
export * as messages from "./messages/index.js";

/** The vocabulary the roots above are generated over. */
export const VOCABULARY = ${JSON.stringify(bundle.vocabulary)} as const;
`,
  );

  // The registry's messages by the name a caller reaches for: the family without
  // its namespace — `agent.planner-surface@1` is `PlannerSurface` — at its latest
  // version, and `<Name>V<n>` at every version.
  const shortName = (id) => pascal(id.slice(id.indexOf(".") + 1, id.indexOf("@")));
  const latest = new Map();
  for (const id of messageIds) {
    const [family, version] = id.split("@");
    const name = shortName(id);
    const held = latest.get(name);
    if (held !== undefined && held.family !== family) {
      throw new Error(
        `the messages ${held.id} and ${id} both become schemas.${name}; extend the naming in scripts/generate.mjs to tell them apart`,
      );
    }
    if (held === undefined || Number(version) > held.version) {
      latest.set(name, { id, family, version: Number(version) });
    }
  }
  files.set(
    "schemas.ts",
    `${BANNER}
// Each export is a message definition (id, Zod schema, JSON Schema, parse) and the
// type it describes, so \`client.next(queue, { type: schemas.PlannerSurface })\` is typed.
${messageIds
  .map(
    (id) =>
      `export { ${messageType(id)} as ${shortName(id)}V${id.split("@")[1]} } from "./messages/${kebab(id)}.js";`,
  )
  .join("\n")}
${[...latest]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(
    ([name, { id }]) =>
      `export { ${messageType(id)} as ${name} } from "./messages/${kebab(id)}.js";`,
  )
  .join("\n")}
`,
  );
  files.set("index.ts", `${files.get("index.ts")}export * as schemas from "./schemas.js";\n`);

  const formatted = new Map();
  for (const [name, source] of files) {
    formatted.set(
      name,
      await format(source, { parser: "typescript", printWidth: 100, endOfLine: "lf" }),
    );
  }
  return formatted;
}

function listed(dir, prefix = "") {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? listed(join(dir, entry.name), `${prefix}${entry.name}/`)
      : [`${prefix}${entry.name}`],
  );
}

/** The first line two texts differ at, as a one-line hint. */
function firstDifference(expected, actual) {
  const want = expected.split("\n");
  const have = actual.split("\n");
  for (let line = 0; line < Math.max(want.length, have.length); line += 1) {
    if (want[line] !== have[line]) {
      const show = (text) =>
        text === undefined ? "<end of file>" : JSON.stringify(text.slice(0, 120));
      return `line ${line + 1}: committed ${show(have[line])}, generated ${show(want[line])}`;
    }
  }
  return "the files differ";
}

const bundle = schemaBundle({ script: "generate", rerun: RERUN });
let files;
try {
  files = await generate(bundle);
} catch (error) {
  const unsupported = error instanceof UnsupportedSchema;
  const kind = unsupported ? "unsupported schema construct" : "generation failed";
  const action = unsupported
    ? "teach scripts/zod-generator.mjs the construct named above, or express the Rust schema without it"
    : "fix the schema or the generator the error above names";
  console.error(`generate: ${kind}: ${error.message}\n  fix: ${action}, then rerun \`${RERUN}\``);
  process.exit(1);
}

const shown = (name) => relative(process.cwd(), join(out, name)) || name;
if (check) {
  const stale = [];
  for (const [name, content] of files) {
    const path = join(out, name);
    if (!existsSync(path)) stale.push(`${shown(name)} is missing`);
    else {
      const committed = readFileSync(path, "utf8");
      if (committed !== content)
        stale.push(`${shown(name)} is stale (${firstDifference(content, committed)})`);
    }
  }
  for (const name of listed(out)) {
    if (!files.has(name)) stale.push(`${shown(name)} is no longer generated`);
  }
  if (stale.length > 0) {
    for (const line of stale) console.error(`generate:check: ${line}`);
    console.error(
      `generate:check: the generated contract differs from the Rust bundle; run \`${RERUN}\` and commit the result`,
    );
    process.exit(1);
  }
} else {
  rmSync(out, { recursive: true, force: true });
  for (const [name, content] of files) {
    mkdirSync(dirname(join(out, name)), { recursive: true });
    writeFileSync(join(out, name), content);
  }
}
