# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""Every message the registry holds, by id."""

from pydantic import BaseModel

from . import (
    agent_artifact_ref_v1,
    agent_command_outcome_v1,
    agent_event_envelope_v1,
    agent_event_envelope_v2,
    agent_event_filter_v1,
    agent_labels_v1,
    agent_note_v1,
    agent_onejudge_frame_assess_v6,
    agent_onejudge_frame_judge_v6,
    agent_onejudge_frame_respond_v6,
    agent_onejudge_frame_supervisor_v6,
    agent_onejudge_frame_user_v6,
    agent_planner_surface_v1,
    agent_queued_commands_v1,
    agent_queued_reply_v1,
    agent_reply_envelope_v2,
    agent_reply_envelope_v3,
    bus_resident_protocol_v1,
    onemessagebus_transport_hello_v1,
    onemessagebus_transport_reply_v1,
    onemessagebus_transport_request_v1,
)

MESSAGES: dict[str, type[BaseModel]] = {
    "agent.artifact-ref@1": agent_artifact_ref_v1.ArtifactRef,
    "agent.command-outcome@1": agent_command_outcome_v1.CommandOutcome,
    "agent.event-envelope@1": agent_event_envelope_v1.Envelope,
    "agent.event-envelope@2": agent_event_envelope_v2.Envelope,
    "agent.event-filter@1": agent_event_filter_v1.Filter,
    "agent.labels@1": agent_labels_v1.Labels,
    "agent.note@1": agent_note_v1.Note,
    "agent.onejudge-frame.assess@6": agent_onejudge_frame_assess_v6.AssessFrame,
    "agent.onejudge-frame.judge@6": agent_onejudge_frame_judge_v6.JudgeFrame,
    "agent.onejudge-frame.respond@6": agent_onejudge_frame_respond_v6.RespondFrame,
    "agent.onejudge-frame.supervisor@6": agent_onejudge_frame_supervisor_v6.SupervisorFrame,
    "agent.onejudge-frame.user@6": agent_onejudge_frame_user_v6.UserFrame,
    "agent.planner-surface@1": agent_planner_surface_v1.Surface,
    "agent.queued-commands@1": agent_queued_commands_v1.QueuedCommands,
    "agent.queued-reply@1": agent_queued_reply_v1.QueuedReply,
    "agent.reply-envelope@2": agent_reply_envelope_v2.ReplyEnvelope,
    "agent.reply-envelope@3": agent_reply_envelope_v3.ReplyEnvelope,
    "bus.resident-protocol@1": bus_resident_protocol_v1.ResidentLine,
    "onemessagebus.transport-hello@1": onemessagebus_transport_hello_v1.PluginHello,
    "onemessagebus.transport-reply@1": onemessagebus_transport_reply_v1.PluginReply,
    "onemessagebus.transport-request@1": onemessagebus_transport_request_v1.PluginRequest,
}
