# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""Every message the registry holds, by id."""

from pydantic import BaseModel

from . import (
    bus_resident_protocol_v1,
    onemessagebus_transport_hello_v1,
    onemessagebus_transport_reply_v1,
    onemessagebus_transport_request_v1,
)

MESSAGES: dict[str, type[BaseModel]] = {
    "bus.resident-protocol@1": bus_resident_protocol_v1.ResidentLine,
    "onemessagebus.transport-hello@1": onemessagebus_transport_hello_v1.PluginHello,
    "onemessagebus.transport-reply@1": onemessagebus_transport_reply_v1.PluginReply,
    "onemessagebus.transport-request@1": onemessagebus_transport_request_v1.PluginRequest,
}
