# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class CommandResult(BaseModel):
    """
    The answer to one command of an envelope.
    """

    index: int = Field(..., ge=0)
    """
    Its index in the envelope's `commands`.
    """
    op: str
    """
    Its op.
    """
    outcome: Literal["applied", "validated", "delivered", "refused"]
    """
    What became of it.
    """
    reason: str | None = None
    """
    Why it refused, or what refused around it.
    """


class CommandOutcome(BaseModel):
    """
    The reconciler's answer to one envelope, as `command-outcomes.jsonl` holds
    it.
    """

    applied: bool
    """
    Whether every command in it was applied.
    """
    id: int = Field(..., ge=0)
    """
    The envelope it answers.
    """
    reason: str | None = None
    """
    Why not.
    """
    results: list[CommandResult] | None = None
    """
    One entry per command, in order. Omitted when empty.
    """
