# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Skill(BaseModel):
    """
    The skill a `respond` frame runs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instructions: str
    """
    Its instructions.
    """
    name: str
    """
    Its name.
    """
    path: str
    """
    Its directory.
    """


class ToolEvent(BaseModel):
    """
    One normalized tool event of an assistant turn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    index: Annotated[int | None, Field(ge=0)] = 0
    """
    Its position within the run.
    """
    input: Any | None = None
    """
    The structured tool arguments.
    """
    kind: Literal["tool_call", "tool_result"]
    """
    `tool_call` or `tool_result`.
    """
    name: str | None = None
    """
    The normalized tool name, where knowable.
    """
    output: str | None = None
    """
    The result text, when the transcript exposed it.
    """
    tool_call_id: str | None = None
    """
    The harness's own identity for the call.
    """


class ConversationMessage(BaseModel):
    """
    One turn of the conversation a frame carries.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    content: str
    """
    Its text.
    """
    events: list[ToolEvent] | None = None
    """
    The tool events taken producing it; omitted when there are none.
    """
    role: Literal["user", "assistant", "system"]
    """
    Who produced it.
    """


class RespondFrame(BaseModel):
    """
    A `respond` frame: run one skill turn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    messages: list[ConversationMessage]
    """
    The transcript so far.
    """
    op: Literal["respond"]
    """
    The operation this frame asks for.
    """
    session: str | None = None
    """
    The caller-owned session name.
    """
    skill: Skill
    """
    The skill.
    """
