# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict

from ..domain import Author


class Command(BaseModel):
    """
    One graph edit, discriminated by op. Its other fields are the op's own; a settle may name the landing it was decided from.
    """

    landing: str | None = None
    """
    Where a settled node's work landed: a change request URL or a commit id.
    """
    op: str
    """
    Which edit this is.
    """


class ReplyEnvelope(BaseModel):
    """
    A reply on the planner channel at version 3: version 2 plus one optional field, a settle command's landing. Additive, so an envelope written against 2 is a complete envelope at 3.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    author: Author | None = None
    """
    Who wrote the reply. Omitted, the planner.
    """
    commands: list[Command] | None = None
    """
    The graph edits, reconciled in order.
    """
    completion: bool | None = None
    """
    The verdict: whether the author considers the run complete.
    """
    message: str | None = None
    """
    The verdict's message to the orchestrator.
    """
    reason: str | None = None
    """
    Why the author reached that verdict.
    """
    version: Literal[3] | None = None
    """
    The reply envelope version this document was written against.
    """
