# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict

from ..domain import Author


class Command(BaseModel):
    """
    One graph edit, discriminated by op. Its other fields are the op's own.
    """

    op: str
    """
    Which edit this is.
    """


class ReplyEnvelope(BaseModel):
    """
    A reply on the planner channel at version 2: the verdict half (completion, message, reason) and the command half (commands), either or both. The shape is onepipeline's; the meaning of each command's op is onepipeline's to define.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    author: Author | None = None
    """
    Who wrote the reply. Omitted, the planner.
    """
    commands: list[Command] | None = None
    """
    The graph edits, reconciled in order.
    """
    completion: bool | None = None
    """
    The verdict: whether the author considers the run complete.
    """
    message: str | None = None
    """
    The verdict's message to the orchestrator.
    """
    reason: str | None = None
    """
    Why the author reached that verdict.
    """
    version: Literal[2] | None = None
    """
    The reply envelope version this document was written against.
    """
