# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class Correlation(RootModel[str]):
    root: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    Which question a reply answers: the token the bus minted when it was asked.
    """


class Surface(BaseModel):
    """
    One planner surface, as `surfaces.jsonl` and `queue.json` hold it.
    """

    abandoned: bool | None = None
    """
    Whether nobody is listening for its answer any more. Omitted while false.
    """
    asker: str | None = None
    """
    Who raised it, when a session naming an asker did. Omitted while absent.
    """
    blocking: bool
    """
    Whether the run waits on its answer.
    """
    correlation: Correlation | None = None
    """
    The correlation a reply echoes to answer it, when it was raised as a
    question (`onemessagebus::ask`). Omitted while absent, so a surface
    raised any other way is written byte for byte as `onepipeline` writes it.
    """
    id: int = Field(..., ge=0)
    """
    Allocated by the queue: one past the highest the log has queued.
    """
    kind: str
    """
    What it is asking about.
    """
    message: str
    """
    Its text.
    """
    queued_at: int = Field(..., ge=0)
    """
    When it was queued, in epoch milliseconds.
    """
    source: str
    """
    What raised it: see [`source`].
    """
    workstream: str | None = None
    """
    The node that provoked it.
    """
