# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Note(BaseModel):
    """
    One note: what the worker reads, who it is for, and the property it binds.

    Built through [`Note::new`] / [`Note::to`] / [`Note::binding`] and in no other
    way — `non_exhaustive` closes the struct literal, and deserialization goes
    through the same conversion — so a note whose text nobody can read, or whose
    criterion is unusable, is unrepresentable rather than representable and refused
    somewhere later.
    """

    addressee: Literal["worker", "supervisor", "both"]
    """
    Who a note is for.

    Required; there is no default, because a note whose addressee is guessed is a
    note the judge may read as an instruction to itself. One run saw a simulated
    user compose a four-point "manager ruling" in-conversation and instruct the
    worker to post it over the run channel, and the worker complied.
    """
    criterion: str | None = None
    text: str


class DeliveredNote(BaseModel):
    """
    One note as it was handed to a party, with the party it reached.
    """

    delivered_to: Literal["worker", "supervisor"]
    """
    The party that was handed it — **not** the same thing as its addressee: a
    note is delivered to whoever is live, and the addressee is what the
    recipient is told the note is *for*.
    """
    note: Note
    """
    The note itself, addressee included.
    """


class ToolEvent(BaseModel):
    """
    One normalized tool event of an assistant turn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    index: Annotated[int | None, Field(ge=0)] = 0
    """
    Its position within the run.
    """
    input: Any | None = None
    """
    The structured tool arguments.
    """
    kind: Literal["tool_call", "tool_result"]
    """
    `tool_call` or `tool_result`.
    """
    name: str | None = None
    """
    The normalized tool name, where knowable.
    """
    output: str | None = None
    """
    The result text, when the transcript exposed it.
    """
    tool_call_id: str | None = None
    """
    The harness's own identity for the call.
    """


class ConversationMessage(BaseModel):
    """
    One turn of the conversation a frame carries.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    content: str
    """
    Its text.
    """
    events: list[ToolEvent] | None = None
    """
    The tool events taken producing it; omitted when there are none.
    """
    role: Literal["user", "assistant", "system"]
    """
    Who produced it.
    """


class SupervisorFrame(BaseModel):
    """
    A `supervisor` frame: decide completion, or produce the next user turn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    done_when: str | None = None
    """
    The criterion actually in force.
    """
    history_name: str
    """
    The recording's name.
    """
    messages: list[ConversationMessage]
    """
    The transcript so far.
    """
    notes: list[DeliveredNote] | None = None
    """
    Every note delivered so far (v5); omitted when none has been.
    """
    op: Literal["supervisor"]
    """
    The operation this frame asks for.
    """
    persona: str
    """
    The supervisor's persona.
    """
    session: str | None = None
    """
    The judge's caller-owned session name.
    """
    task: str
    """
    The task the conversation is about; its opening line names the run.
    """
    worktree: str
    """
    The worktree the recording is kept under.
    """
