# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from ..domain import Author


class Correlation(RootModel[str]):
    root: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
    """
    Which question a reply answers: the token the bus minted when it was asked.
    """


class ReplyEnvelope(BaseModel):
    """
    One reply envelope: a verdict, a list of graph edits, or both.

    Its commands are carried as JSON, in the order and with the fields their
    author wrote: which ops exist and what each means are `onepipeline`'s, and
    this crate reads only each command's `op`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    author: Author | None = None
    """
    Who wrote it. Omitted, the planner.
    """
    commands: list[dict[str, Any]] | None = None
    """
    The graph edits, each an object naming its `op`.
    """
    completion: bool | None = None
    """
    The verdict: whether the author considers the run complete.
    """
    message: str | None = None
    """
    The verdict's message.
    """
    reason: str | None = None
    """
    Why the author reached that verdict.
    """
    version: int | None = Field(None, ge=0)
    """
    The version it was written against, read at [`REPLY_ENVELOPE_VERSION`].
    """


class QueuedReply(BaseModel):
    """
    One reply as `replies.jsonl` holds it.
    """

    at: int = Field(..., ge=0)
    """
    When it was written, in epoch milliseconds.
    """
    correlation: Correlation | None = None
    """
    The correlation of the question it answers, when it answers one asked
    through `onemessagebus::ask`. Omitted while absent.
    """
    id: int = Field(..., ge=0)
    """
    The number of replies before it.
    """
    reply: ReplyEnvelope
    """
    The envelope.
    """
