# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Evidence(BaseModel):
    """
    The evidence a `judge` frame names (protocol v6).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    history_files: list[str]
    """
    The exact history artifact paths.
    """
    worktree: str | None = None
    """
    The skill's working directory.
    """


class ToolEvent(BaseModel):
    """
    One normalized tool event of an assistant turn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    index: Annotated[int | None, Field(ge=0)] = 0
    """
    Its position within the run.
    """
    input: Any | None = None
    """
    The structured tool arguments.
    """
    kind: Literal["tool_call", "tool_result"]
    """
    `tool_call` or `tool_result`.
    """
    name: str | None = None
    """
    The normalized tool name, where knowable.
    """
    output: str | None = None
    """
    The result text, when the transcript exposed it.
    """
    tool_call_id: str | None = None
    """
    The harness's own identity for the call.
    """


class ConversationMessage(BaseModel):
    """
    One turn of the conversation a frame carries.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    content: str
    """
    Its text.
    """
    events: list[ToolEvent] | None = None
    """
    The tool events taken producing it; omitted when there are none.
    """
    role: Literal["user", "assistant", "system"]
    """
    Who produced it.
    """


class JudgeFrame1(BaseModel):
    """
    A boolean completion criterion.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["judge"]
    """
    The operation this frame asks for.
    """
    criterion: str
    """
    The criterion.
    """
    evidence: Evidence | None = None
    """
    The evidence (v6); omitted without context.
    """
    kind: Literal["boolean"]
    messages: list[ConversationMessage]
    """
    The transcript.
    """


class JudgeFrame2(BaseModel):
    """
    A numeric score with required bounds.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["judge"]
    """
    The operation this frame asks for.
    """
    criterion: str
    """
    The criterion.
    """
    evidence: Evidence | None = None
    """
    The evidence (v6); omitted without context.
    """
    kind: Literal["numeric"]
    max: float
    """
    The score's ceiling.
    """
    messages: list[ConversationMessage]
    """
    The transcript.
    """
    min: float
    """
    The score's floor.
    """


class JudgeFrame(RootModel[JudgeFrame1 | JudgeFrame2]):
    root: Annotated[JudgeFrame1 | JudgeFrame2, Field(title="JudgeFrame")]
    """
    A `judge` frame: score a criterion against the transcript.
    """
