# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class QueuedCommands(BaseModel):
    """
    One command envelope as `commands.jsonl` holds it.
    """

    author: Literal["planner", "monitor"] | None = "planner"
    """
    Who submitted it.
    """
    commands: list[dict[str, Any]]
    """
    The commands, each an object naming its `op`.
    """
    id: int = Field(..., ge=0)
    """
    The number of envelopes before it.
    """
