# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ArtifactRef(BaseModel):
    """
    Evidence too large for a payload: stored by the producing library and
    referenced by id, to be read back through that library.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bytes: int = Field(..., ge=0)
    """
    Size of the stored artifact.
    """
    id: str
    """
    Identifier, unique within the producing library's store.
    """
    kind: str
    """
    What the artifact is — a gate log, a check log, a transcript, a report.
    """


class Labels(BaseModel):
    """
    The reserved label keys, plus whatever else a producer stamped.

    Reserved keys are absent rather than empty when unknown, so an enricher can
    tell "not stamped" from "stamped empty". The extras are flattened beside
    them, in the order they were stamped.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    member: str | None = None
    """
    Which member of a conversation produced the event.
    """
    node: str | None = None
    """
    The graph node being executed.
    """
    persona: str | None = None
    """
    The persona that member is running under.
    """
    round: int | None = Field(None, ge=0)
    """
    The round within the run.
    """
    run_id: str | None = None
    """
    The run this event belongs to.
    """
    step: str | None = None
    """
    The step within a node that runs several in sequence.
    """


class Envelope(BaseModel):
    """
    One event, as a producing process writes it and as a consumer reads it.

    Merge order across streams is `(ts, stream, seq)`. A consumer detects loss
    as a per-stream [`seq`](Self::seq) gap; there is no cross-stream promise
    beyond the timestamps.

    The type parameter is the [`Vocabulary`] the envelope is written over: it
    decides the source words, the dimensions carried between `kind` and
    `labels`, and the label set. Deserialization refuses an unknown top-level
    field, a `seq` that is not an unsigned integer, a source word the vocabulary
    does not admit, and a missing required field — each by name.
    """

    artifacts: list[ArtifactRef] | None = Field([], validate_default=True)
    """
    Evidence stored by the producing library and referenced by id.
    """
    kind: str
    """
    What happened, as its producer named it.
    """
    labels: Labels | None = Field({}, validate_default=True)
    """
    The reserved keys the vocabulary declares plus free-form extras.
    Producers stamp what they know; enrichers never rewrite.
    """
    payload: dict[str, Any] | None = {}
    """
    Kind-specific detail. Text fields are bounded by
    [`MAX_PAYLOAD_TEXT_BYTES`](crate::MAX_PAYLOAD_TEXT_BYTES); larger
    evidence is an [`ArtifactRef`].
    """
    phase: Literal["development", "integrate", "review", "release"] | None = None
    """
    Which part of a change's life the event belongs to, as its producer
    classified it.
    """
    seq: int = Field(..., ge=0)
    """
    Monotonic per [`stream`](Self::stream).
    """
    source: Literal["agentgraph", "vcs", "pipeline"]
    """
    What produced the event, in the vocabulary's words.
    """
    stream: str
    """
    Unique id of the producing process.
    """
    ts: str
    """
    RFC 3339, millisecond precision, UTC.
    """
    v: Literal[2] = Field(..., ge=0)
    """
    The envelope schema version the producer wrote against.
    """
