# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class Note(BaseModel):
    """
    One note: what the worker reads, who it is for, and the property it binds.

    Built through [`Note::new`] / [`Note::to`] / [`Note::binding`] and in no other
    way — `non_exhaustive` closes the struct literal, and deserialization goes
    through the same conversion — so a note whose text nobody can read, or whose
    criterion is unusable, is unrepresentable rather than representable and refused
    somewhere later.
    """

    addressee: Literal["worker", "supervisor", "both"]
    """
    Who a note is for.

    Required; there is no default, because a note whose addressee is guessed is a
    note the judge may read as an instruction to itself. One run saw a simulated
    user compose a four-point "manager ruling" in-conversation and instruct the
    worker to post it over the run channel, and the worker complied.
    """
    criterion: str | None = None
    text: str
