# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ArtifactRef(BaseModel):
    """
    Evidence too large for a payload: stored by the producing library and
    referenced by id, to be read back through that library.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bytes: Annotated[int, Field(ge=0)]
    """
    Size of the stored artifact.
    """
    id: str
    """
    Identifier, unique within the producing library's store.
    """
    kind: str
    """
    What the artifact is — a gate log, a check log, a transcript, a report.
    """
