# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Labels(BaseModel):
    """
    The reserved label keys, plus whatever else a producer stamped.

    Reserved keys are absent rather than empty when unknown, so an enricher can
    tell "not stamped" from "stamped empty". The extras are flattened beside
    them, in the order they were stamped.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    member: str | None = None
    """
    Which member of a conversation produced the event.
    """
    node: str | None = None
    """
    The graph node being executed.
    """
    persona: str | None = None
    """
    The persona that member is running under.
    """
    round: Annotated[int | None, Field(ge=0)] = None
    """
    The round within the run.
    """
    run_id: str | None = None
    """
    The run this event belongs to.
    """
    step: str | None = None
    """
    The step within a node that runs several in sequence.
    """
