# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Matcher(BaseModel):
    """
    One matcher: every field it names must hold of an envelope, and a field it
    does not name is not consulted.
    """

    kind: str | None = None
    """
    A glob over the kind's kebab-case wire string, where `*` stands for any
    run of characters including none and every other character is itself.
    """
    member: str | None = None
    """
    The `member` label.
    """
    node: str | None = None
    """
    The `node` label.
    """
    persona: str | None = None
    """
    The `persona` label.
    """
    phase: Literal["development", "integrate", "review", "release"] | None = None
    """
    The phase the envelope was stamped at.
    """
    run_id: str | None = None
    """
    The `run_id` label.
    """
    source: Literal["agentgraph", "vcs", "pipeline"] | None = None
    """
    The producer, by exact equality.
    """
    step: str | None = None
    """
    The `step` label.
    """


class Filter(BaseModel):
    """
    Which envelopes pass.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    exclude: list[Matcher] | None = None
    """
    Matchers that reject. A match here rejects whatever
    [`include`](Self::include) said, so a broad include beside a narrow
    exclude is how "all of this except that" is written.
    """
    include: list[Matcher] | None = None
    """
    Matchers an envelope satisfies one of to pass. Absent or empty admits
    every envelope, so a filter that only rejects need name nothing here.
    """
