# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ResidentAnswer(BaseModel):
    """
    What a request that did what it was asked answered.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int = Field(..., ge=0)
    """
    The request answered.
    """
    ok: Any
    """
    The verb's output: the document of a `json` verb, the list of lines of a
    `jsonl` verb, the text of a `text` verb or a `--format text` rendering —
    and, for `subscribe`, `"until"` when its predicate held or `"cancelled"`.
    """


class ResidentCancel(BaseModel):
    """
    Stop the streaming request `id` names.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cancel: Literal[True]
    """
    Always `true`.
    """
    id: int = Field(..., ge=0)
    """
    The request to stop.
    """


class ResidentEvent(BaseModel):
    """
    One line a streaming request produced: a `subscribe` log record.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event: Any
    """
    The line, as the verb prints it: a `{position, record}` log record, or its
    text rendering under `--format text`.
    """
    id: int = Field(..., ge=0)
    """
    The streaming request.
    """


class ResidentRefusal(BaseModel):
    """
    Why a request was refused.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    exit: Literal[1, 2]
    """
    The exit code the command line gives this refusal.
    """
    message: str
    """
    The command line's refusal, as it writes it after `onemessagebus: `.
    """
    output: Any | None = None
    """
    The document the verb printed before refusing — `ask`'s answer,
    `validate`'s verdict — when it printed one.
    """


class ResidentFailure(BaseModel):
    """
    A request the resident refused, in the command line's own words.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: ResidentRefusal
    """
    Why.
    """
    id: int | None = Field(None, ge=0)
    """
    The request refused; `null` for a line that named no id to answer.
    """


class ResidentRequest(BaseModel):
    """
    Run one capability, as its SDK method, with its options.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    args: dict[str, Any] | None = None
    """
    The capability's options, keyed as its options root keys them (camelCase).
    """
    id: int = Field(..., ge=0)
    """
    Chosen by the client and echoed on every line answering this request.
    """
    input: str | None = None
    """
    The bytes the verb would read on stdin: a payload, a question, a reply, a
    message or a codec's frames.
    """
    verb: Literal[
        "schemaList",
        "schemaCheck",
        "schemaGen",
        "schemaRegister",
        "eventsMerge",
        "eventsEmit",
        "deliver",
        "inboxCarried",
        "send",
        "next",
        "reply",
        "subscribe",
        "status",
        "transports",
        "validate",
        "ask",
        "serve",
        "schemas",
        "schemasClear",
        "schemasFetch",
    ]
    """
    The capability to run, by its SDK method: one of the manifest's and no other.
    """


class ResidentLine(
    RootModel[ResidentRequest | ResidentCancel | ResidentAnswer | ResidentFailure | ResidentEvent]
):
    root: ResidentRequest | ResidentCancel | ResidentAnswer | ResidentFailure | ResidentEvent = (
        Field(..., title="ResidentLine")
    )
    """
    One line of the resident protocol, in either direction.
    """
