# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class TransportConfig(BaseModel):
    """
    The `transport` block of a configuration: the kind, the directory a
    directory-backed transport keeps its queues in, and whatever else the kind
    takes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dir: str | None = None
    """
    The directory a directory-backed transport keeps its queues in.
    """
    kind: str
    """
    The kind: `local`, `memory`, or a kind registered in-process or served
    by a plugin.
    """


class PluginHello(BaseModel):
    """
    The client's first line: which protocol, at which version, opening which
    transport.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    config: TransportConfig
    """
    The `transport` block of the configuration, with `dir` resolved.
    """
    protocol: str
    """
    Always [`PROTOCOL`].
    """
    version: Annotated[int, Field(ge=0)]
    """
    The version the client speaks: [`PROTOCOL_VERSION`].
    """
