# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class FingerprintItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Position(RootModel[int]):
    root: Annotated[int, Field(ge=0)]
    """
    Where in a queue a record ends: opaque to consumers, and meaningful only to
    the transport that handed it out.

    A consumer receives positions from [`Transport::append`] and
    [`Transport::read`] and hands them back; it never builds one from a number
    it made up. It serializes as its token so a cursor survives a process.
    [`from_token`](Self::from_token) and [`token`](Self::token) exist for a
    transport's own implementation: [`LocalTransport`]'s token is the byte offset
    at a record boundary, [`MemoryTransport`]'s the count of records before it.
    """


class PluginRequestAppend(BaseModel):
    """
    [`Transport::append`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["append"]
    queue: str
    """
    The queue.
    """
    record: str
    """
    The record.
    """


class PluginRequestBeginExclusive(BaseModel):
    """
    Open [`Transport::exclusive`]'s section over a queue.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["begin_exclusive"]
    queue: str
    """
    The queue.
    """


class PluginRequestCommit(BaseModel):
    """
    [`Transport::commit`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    at: Annotated[int, Field(ge=0)]
    """
    Where it has read up to.
    """
    consumer: str
    """
    The consumer.
    """
    op: Literal["commit"]
    queue: str
    """
    The queue.
    """


class PluginRequestCursor(BaseModel):
    """
    [`Transport::cursor`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    consumer: str
    """
    The consumer.
    """
    op: Literal["cursor"]
    queue: str
    """
    The queue.
    """


class PluginRequestDocument(BaseModel):
    """
    [`Transport::document`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    The document.
    """
    op: Literal["document"]
    queue: str
    """
    The queue.
    """


class PluginRequestEndExclusive(BaseModel):
    """
    End the section the matching `begin_exclusive` opened.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    failed: bool
    """
    Whether the body failed, so the section ends with its failure.
    """
    op: Literal["end_exclusive"]
    queue: str
    """
    The queue.
    """


class PluginRequestFingerprint(BaseModel):
    """
    [`Transport::fingerprint`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["fingerprint"]
    queue: str
    """
    The queue.
    """


class PluginRequestRead(BaseModel):
    """
    [`Transport::read`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    from_: Annotated[Position | None, Field(alias="from")] = None
    """
    Read after this position; from the start when absent.
    """
    limit: Annotated[int, Field(ge=0)]
    """
    At most this many records.
    """
    op: Literal["read"]
    queue: str
    """
    The queue.
    """


class PluginRequestReplaceDocument(BaseModel):
    """
    [`Transport::replace_document`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bytes: str
    """
    Its new contents.
    """
    name: str
    """
    The document.
    """
    op: Literal["replace_document"]
    queue: str
    """
    The queue.
    """


class PluginRequestWaitForChange(BaseModel):
    """
    [`Transport::wait_for_change`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Literal["wait_for_change"]
    queue: str
    """
    The queue.
    """
    since: list[FingerprintItem]
    """
    The fingerprint to wait for it to move from.
    """
    timeout_ms: Annotated[int, Field(ge=0)]
    """
    How long to wait, in milliseconds.
    """


class PluginRequest(
    RootModel[
        PluginRequestAppend
        | PluginRequestRead
        | PluginRequestCursor
        | PluginRequestCommit
        | PluginRequestBeginExclusive
        | PluginRequestEndExclusive
        | PluginRequestFingerprint
        | PluginRequestWaitForChange
        | PluginRequestDocument
        | PluginRequestReplaceDocument
    ]
):
    root: Annotated[
        PluginRequestAppend
        | PluginRequestRead
        | PluginRequestCursor
        | PluginRequestCommit
        | PluginRequestBeginExclusive
        | PluginRequestEndExclusive
        | PluginRequestFingerprint
        | PluginRequestWaitForChange
        | PluginRequestDocument
        | PluginRequestReplaceDocument,
        Field(title="PluginRequest"),
    ]
    """
    One request after the hello, discriminated by `op`: one per [`Transport`]
    method, with `exclusive` split into its opening and its end.

    Records and documents travel as text, so a plugin carries UTF-8 records; a
    record that is not UTF-8 is refused by the client before it is sent.
    """
