# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class FingerprintItem(RootModel[int]):
    root: int = Field(..., ge=0)


class Hello(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocol: str
    """
    Always [`PROTOCOL`].
    """
    version: int = Field(..., ge=0)
    """
    The version the plugin speaks.
    """


class PluginAnswer1(BaseModel):
    """
    The answer to a hello: the plugin speaks this protocol at this version.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hello: Hello


class PluginAnswer5(BaseModel):
    """
    A fingerprint.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    fingerprint: list[FingerprintItem]
    """
    A cheap change token for a queue: two fingerprints of one queue are equal
    when nothing observable about it moved.

    Opaque, like [`Position`]: a transport builds one from whatever it can
    observe cheaply ([`LocalTransport`] from each file's length and modification
    time, as `onepipeline` does), and a consumer only compares them.
    """


class PluginAnswer6(BaseModel):
    """
    A wait for a change saw the queue move: its fingerprint now.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    moved: list[FingerprintItem]
    """
    A cheap change token for a queue: two fingerprints of one queue are equal
    when nothing observable about it moved.

    Opaque, like [`Position`]: a transport builds one from whatever it can
    observe cheaply ([`LocalTransport`] from each file's length and modification
    time, as `onepipeline` does), and a consumer only compares them.
    """


class PluginAnswer7(BaseModel):
    """
    A wait for a change timed out with the queue where it was: its
    fingerprint now.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    unchanged: list[FingerprintItem]
    """
    A cheap change token for a queue: two fingerprints of one queue are equal
    when nothing observable about it moved.

    Opaque, like [`Position`]: a transport builds one from whatever it can
    observe cheaply ([`LocalTransport`] from each file's length and modification
    time, as `onepipeline` does), and a consumer only compares them.
    """


class PluginAnswer8(BaseModel):
    """
    A document's contents, or `null` where there is none.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    document: str | None


class PluginErrorProtocol(BaseModel):
    """
    A request the plugin could not read, or one out of its place.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["protocol"]
    message: str
    """
    What the plugin said.
    """


class PluginErrorRefused(BaseModel):
    """
    Anything else the transport refused.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["refused"]
    message: str
    """
    What the plugin said.
    """


class Position(RootModel[int]):
    root: int = Field(..., ge=0)
    """
    Where in a queue a record ends: opaque to consumers, and meaningful only to
    the transport that handed it out.

    A consumer receives positions from [`Transport::append`] and
    [`Transport::read`] and hands them back; it never builds one from a number
    it made up. It serializes as its token so a cursor survives a process.
    [`from_token`](Self::from_token) and [`token`](Self::token) exist for a
    transport's own implementation: [`LocalTransport`]'s token is the byte offset
    at a record boundary, [`MemoryTransport`]'s the count of records before it.
    """


class PluginAnswer2(BaseModel):
    """
    Where an appended record landed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    position: int = Field(..., ge=0)
    """
    Where in a queue a record ends: opaque to consumers, and meaningful only to
    the transport that handed it out.

    A consumer receives positions from [`Transport::append`] and
    [`Transport::read`] and hands them back; it never builds one from a number
    it made up. It serializes as its token so a cursor survives a process.
    [`from_token`](Self::from_token) and [`token`](Self::token) exist for a
    transport's own implementation: [`LocalTransport`]'s token is the byte offset
    at a record boundary, [`MemoryTransport`]'s the count of records before it.
    """


class PluginAnswer4(BaseModel):
    """
    A consumer's cursor, or `null` for one that has read nothing.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: Position | None


class PluginErrorNotABoundary(BaseModel):
    """
    [`TransportError::NotABoundary`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["not_a_boundary"]
    message: str
    """
    What the plugin said.
    """
    position: int = Field(..., ge=0)
    """
    The position asked for.
    """
    queue: str
    """
    The queue.
    """


class PluginErrorPastEnd(BaseModel):
    """
    [`TransportError::PastEnd`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    end: int = Field(..., ge=0)
    """
    Where the queue ends.
    """
    kind: Literal["past_end"]
    message: str
    """
    What the plugin said.
    """
    position: int = Field(..., ge=0)
    """
    The position asked for.
    """
    queue: str
    """
    The queue.
    """


class PluginStored(BaseModel):
    """
    One record of a [`PluginAnswer::Batch`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    after: int = Field(..., ge=0)
    """
    The position after it.
    """
    record: str
    """
    The record.
    """


class PluginTorn(BaseModel):
    """
    The torn record of a [`PluginAnswer::Batch`].
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    at: int = Field(..., ge=0)
    """
    Where it starts.
    """
    bytes: int = Field(..., ge=0)
    """
    How many bytes of it there are.
    """


class Batch(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    records: list[PluginStored]
    """
    The whole records, oldest first.
    """
    torn: PluginTorn | None = None
    """
    A torn record after them.
    """


class PluginAnswer3(BaseModel):
    """
    The records a read found.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    batch: Batch


class PluginReply1(BaseModel):
    """
    The request was done.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ok: (
        PluginAnswer1
        | PluginAnswer2
        | PluginAnswer3
        | PluginAnswer4
        | PluginAnswer5
        | PluginAnswer6
        | PluginAnswer7
        | PluginAnswer8
        | Literal["done"]
    )
    """
    What a request that was done answers.
    """


class PluginReply2(BaseModel):
    """
    It was not.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: PluginErrorPastEnd | PluginErrorNotABoundary | PluginErrorRefused | PluginErrorProtocol
    """
    Why a request was not done, discriminated by `kind`, in words the client
    turns back into a [`TransportError`]. `past_end` and `not_a_boundary` carry
    the queue and the positions, so a queue reading the reply can fold its log
    again; a reply missing one of them is not a reply.
    """


class PluginReply(RootModel[PluginReply1 | PluginReply2]):
    root: PluginReply1 | PluginReply2 = Field(..., title="PluginReply")
    """
    One reply: what was asked for, or why not.
    """
