# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""The generated model of every message the registry holds, by its family's name.

`PlannerSurface` is `agent.planner-surface@1`'s model at the latest version the registry
holds, and `PlannerSurfaceV1` names that version; `messages.MESSAGES` maps each id
to its model.
"""

from ._generated.messages.agent_artifact_ref_v1 import ArtifactRef as ArtifactRefV1
from ._generated.messages.agent_command_outcome_v1 import CommandOutcome as CommandOutcomeV1
from ._generated.messages.agent_event_envelope_v1 import Envelope as EventEnvelopeV1
from ._generated.messages.agent_event_envelope_v2 import Envelope as EventEnvelopeV2
from ._generated.messages.agent_event_filter_v1 import Filter as EventFilterV1
from ._generated.messages.agent_labels_v1 import Labels as LabelsV1
from ._generated.messages.agent_note_v1 import Note as NoteV1
from ._generated.messages.agent_onejudge_frame_assess_v6 import AssessFrame as OnejudgeFrameAssessV6
from ._generated.messages.agent_onejudge_frame_judge_v6 import JudgeFrame as OnejudgeFrameJudgeV6
from ._generated.messages.agent_onejudge_frame_respond_v6 import (
    RespondFrame as OnejudgeFrameRespondV6,
)
from ._generated.messages.agent_onejudge_frame_supervisor_v6 import (
    SupervisorFrame as OnejudgeFrameSupervisorV6,
)
from ._generated.messages.agent_onejudge_frame_user_v6 import UserFrame as OnejudgeFrameUserV6
from ._generated.messages.agent_planner_surface_v1 import Surface as PlannerSurfaceV1
from ._generated.messages.agent_queued_commands_v1 import QueuedCommands as QueuedCommandsV1
from ._generated.messages.agent_queued_reply_v1 import QueuedReply as QueuedReplyV1
from ._generated.messages.agent_reply_envelope_v2 import ReplyEnvelope as ReplyEnvelopeV2
from ._generated.messages.agent_reply_envelope_v3 import ReplyEnvelope as ReplyEnvelopeV3
from ._generated.messages.bus_resident_protocol_v1 import ResidentLine as ResidentProtocolV1
from ._generated.messages.onemessagebus_transport_hello_v1 import PluginHello as TransportHelloV1
from ._generated.messages.onemessagebus_transport_reply_v1 import PluginReply as TransportReplyV1
from ._generated.messages.onemessagebus_transport_request_v1 import (
    PluginRequest as TransportRequestV1,
)

ArtifactRef = ArtifactRefV1
CommandOutcome = CommandOutcomeV1
EventEnvelope = EventEnvelopeV2
EventFilter = EventFilterV1
Labels = LabelsV1
Note = NoteV1
OnejudgeFrameAssess = OnejudgeFrameAssessV6
OnejudgeFrameJudge = OnejudgeFrameJudgeV6
OnejudgeFrameRespond = OnejudgeFrameRespondV6
OnejudgeFrameSupervisor = OnejudgeFrameSupervisorV6
OnejudgeFrameUser = OnejudgeFrameUserV6
PlannerSurface = PlannerSurfaceV1
QueuedCommands = QueuedCommandsV1
QueuedReply = QueuedReplyV1
ReplyEnvelope = ReplyEnvelopeV3
ResidentProtocol = ResidentProtocolV1
TransportHello = TransportHelloV1
TransportReply = TransportReplyV1
TransportRequest = TransportRequestV1

__all__ = [
    "ArtifactRef",
    "ArtifactRefV1",
    "CommandOutcome",
    "CommandOutcomeV1",
    "EventEnvelope",
    "EventEnvelopeV1",
    "EventEnvelopeV2",
    "EventFilter",
    "EventFilterV1",
    "Labels",
    "LabelsV1",
    "Note",
    "NoteV1",
    "OnejudgeFrameAssess",
    "OnejudgeFrameAssessV6",
    "OnejudgeFrameJudge",
    "OnejudgeFrameJudgeV6",
    "OnejudgeFrameRespond",
    "OnejudgeFrameRespondV6",
    "OnejudgeFrameSupervisor",
    "OnejudgeFrameSupervisorV6",
    "OnejudgeFrameUser",
    "OnejudgeFrameUserV6",
    "PlannerSurface",
    "PlannerSurfaceV1",
    "QueuedCommands",
    "QueuedCommandsV1",
    "QueuedReply",
    "QueuedReplyV1",
    "ReplyEnvelope",
    "ReplyEnvelopeV2",
    "ReplyEnvelopeV3",
    "ResidentProtocol",
    "ResidentProtocolV1",
    "TransportHello",
    "TransportHelloV1",
    "TransportReply",
    "TransportReplyV1",
    "TransportRequest",
    "TransportRequestV1",
]
