# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus
# schema bundle. Do not edit: run the generator.
"""The generated model of every message the registry holds, by its family's name.

`TransportHello` is the `onemessagebus.transport-hello` family's model at the latest
version the registry holds, and `TransportHelloV1` names version 1;
`messages.MESSAGES` maps each id to its model.
"""

from ._generated.messages.bus_resident_protocol_v1 import ResidentLine as ResidentProtocolV1
from ._generated.messages.onemessagebus_transport_hello_v1 import PluginHello as TransportHelloV1
from ._generated.messages.onemessagebus_transport_reply_v1 import PluginReply as TransportReplyV1
from ._generated.messages.onemessagebus_transport_request_v1 import (
    PluginRequest as TransportRequestV1,
)

ResidentProtocol = ResidentProtocolV1
TransportHello = TransportHelloV1
TransportReply = TransportReplyV1
TransportRequest = TransportRequestV1

__all__ = [
    "ResidentProtocol",
    "ResidentProtocolV1",
    "TransportHello",
    "TransportHelloV1",
    "TransportReply",
    "TransportReplyV1",
    "TransportRequest",
    "TransportRequestV1",
]
