"""Generate the SDK's wire types and capability manifest from the Rust bundle.

`python scripts/generate.py` rewrites `src/onemessagebus/_generated/` and
`src/onemessagebus/models.py`;
`--check` writes nothing and exits 1 with a unified diff when the committed copy
differs from a fresh generation. Every model is datamodel-code-generator's
rendering of a schema the Rust build owns, so no wire shape is restated by hand:

- `contract.py`: every output root and every options root of the bundle, merged
  into one module (they are generated from one set of Rust types, so a `$defs`
  name two roots share is the same definition, and a disagreement fails here);
- `messages/<id>.py`: every registered message, `bus.resident-protocol@1`
  included, with `messages.MESSAGES` mapping each id to its root model;
- `capabilities.json`: the capability manifest, read as data by the argv builder
  and the resident request builder.

One transform is applied before rendering: a `oneOf` whose branches are objects
told apart by one constant property is hoisted into named definitions,
`<Title><Tag>` (`AskedReply`, `ValidatedPass`), so a tagged union's variants are
importable by name rather than numbered.
"""

from __future__ import annotations

import argparse
import copy
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import warnings
from pathlib import Path
from typing import Any, NoReturn

PACKAGE = Path(__file__).resolve().parents[1]
ROOT = PACKAGE.parents[1]
# The package directory whose `_generated/` and `models.py` the generator owns.
OUTPUT = PACKAGE / "src" / "onemessagebus"
BUNDLE_ARGS = ["run", "-q", "--locked", "-p", "onemessagebus-cli", "--example", "sdk_bundle"]
BUNDLE_TARGET = ROOT / "target" / "sdk-bundle"
RERUN = "bash python/onemessagebus-sdk/scripts/run python scripts/generate.py"
OUTPUT_ROOTS = (
    "envelope",
    "filter",
    "matcher",
    "schema_id",
    "registry_document",
    "schema_list",
    "disposition",
    "carried_entry",
    "config",
    "sent",
    "claimed",
    "replied",
    "log_record",
    "queue_statuses",
    "transport_kinds",
    "validated",
    "asked",
    "codec_response",
)
HEADER = (
    "# Generated by python/onemessagebus-sdk/scripts/generate.py from the onemessagebus\n"
    "# schema bundle. Do not edit: run the generator."
)
# A cargo failure can run to hundreds of lines; its tail is where the error is.
CAUSE_LINES = 20


def fail(message: str) -> NoReturn:
    """Print a bounded diagnostic and exit 1: a stack trace is noise to a gate's reader."""
    print(f"generate.py: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_bundle() -> dict[str, Any]:
    """The bundle, from the Rust build that owns it."""
    cargo = shutil.which("cargo")
    if cargo is None:
        fail("cargo is not on PATH; install the pinned toolchain with `just bootstrap`.")
    try:
        run = subprocess.run(
            [cargo, *BUNDLE_ARGS],
            cwd=ROOT,
            env={**os.environ, "CARGO_TARGET_DIR": str(BUNDLE_TARGET)},
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as error:
        fail(
            f"{cargo} could not be run ({error}); install the pinned toolchain with `just bootstrap`."
        )
    if run.returncode != 0:
        cause = [line for line in run.stderr.splitlines() if line.strip()][-CAUSE_LINES:]
        said = "\n".join(f"    {line}" for line in cause)
        fail(
            "the Rust schema bundle did not build, so there is no contract to read.\n"
            f"  cargo said:\n{said}\n"
            f"  fix: make the bundle build, then rerun `{RERUN}`.\n"
            f"       See it in full with: cargo {' '.join(BUNDLE_ARGS)}"
        )
    try:
        return json.loads(run.stdout)
    except json.JSONDecodeError as error:
        fail(
            f"the bundle example ran but did not print JSON ({error}); `sdk_bundle` must "
            "print the bundle and nothing else."
        )


def pascal(word: str) -> str:
    """`Array_of_QueueStatus` → `ArrayOfQueueStatus`, `planner-surface` → `PlannerSurface`."""
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", word) if part)


def module_for(schema_id: str) -> str:
    """`agent.onejudge-frame.judge@6` → `agent_onejudge_frame_judge_v6`."""
    family, version = schema_id.rsplit("@", 1)
    return f"{re.sub(r'[^A-Za-z0-9]+', '_', family).lower()}_v{version}"


def tag_of(branch: Any) -> str | None:
    """The constant a tagged-union branch is told apart by, when it has exactly one."""
    if not isinstance(branch, dict) or {"$ref", "allOf", "anyOf", "oneOf"} & branch.keys():
        return None
    constants = [
        value["const"]
        for value in branch.get("properties", {}).values()
        if isinstance(value, dict) and isinstance(value.get("const"), str)
    ]
    return constants[0] if len(constants) == 1 else None


def hoist(title: str, schema: dict[str, Any], defs: dict[str, Any]) -> dict[str, Any]:
    """Name the variants of a tagged `oneOf`, folding the parent's own properties into each."""
    branches = schema.get("oneOf")
    if not isinstance(branches, list) or not branches:
        return schema
    tags = [tag_of(branch) for branch in branches]
    if any(tag is None for tag in tags):
        return schema
    parent = {k: v for k, v in schema.items() if k not in ("oneOf", "properties", "required")}
    parent.pop("type", None)
    refs = []
    for branch, tag in zip(branches, tags, strict=True):
        name = f"{title}{pascal(str(tag))}"
        if name in defs:
            raise RuntimeError(f"{title}: the variant {name} names a definition that exists")
        variant = {
            **{k: v for k, v in branch.items() if k not in ("properties", "required")},
            "type": "object",
            "title": name,
            "properties": {**schema.get("properties", {}), **branch.get("properties", {})},
            "required": [*schema.get("required", []), *branch.get("required", [])],
        }
        if "additionalProperties" in schema:
            variant["additionalProperties"] = schema["additionalProperties"]
        defs[name] = variant
        refs.append({"$ref": f"#/$defs/{name}"})
    return {**parent, "oneOf": refs}


def named(document: dict[str, Any]) -> dict[str, Any]:
    """`document` with every tagged union in it and in its `$defs` hoisted."""
    document = copy.deepcopy(document)
    defs: dict[str, Any] = document.get("$defs", {})
    for name in list(defs):
        defs[name] = hoist(name, defs[name], defs)
    root = hoist(pascal(document.get("title", "Model")), document, defs)
    if defs:
        root["$defs"] = defs
    return root


def contract_document(bundle: dict[str, Any]) -> dict[str, Any]:
    """Every output and options root as a named definition of one document."""
    defs: dict[str, Any] = {}
    origin: dict[str, str] = {}

    def comparable(schema: Any) -> Any:
        return {k: v for k, v in schema.items() if k not in ("$schema", "title")}

    def admit(name: str, schema: Any, where: str) -> None:
        if name in defs and comparable(defs[name]) != comparable(schema):
            raise RuntimeError(
                f"the definition {name} differs between {origin[name]} and {where}; "
                "the roots of one bundle must agree on a shared name"
            )
        defs.setdefault(name, schema)
        origin.setdefault(name, where)

    roots = [(root, bundle[root]) for root in OUTPUT_ROOTS]
    roots += [(f"options.{key}", bundle["options"][key]) for key in sorted(bundle["options"])]
    for where, schema in roots:
        document = named(schema)
        for name, definition in document.pop("$defs", {}).items():
            admit(name, definition, where)
        document.pop("$schema", None)
        admit(pascal(document["title"]), document, where)
    return {"title": "Contract", "$defs": dict(sorted(defs.items()))}


def render(document: dict[str, Any], class_name: str | None, destination: Path) -> None:
    """datamodel-code-generator's Pydantic v2 rendering of one document."""
    from datamodel_code_generator import (
        DataModelType,
        Formatter,
        InputFileType,
        LiteralType,
        PythonVersion,
        generate,
    )

    with warnings.catch_warnings():
        # `format: uint64` and friends carry nothing a Python int needs; the
        # `minimum` beside them is what constrains the field.
        warnings.filterwarnings("ignore", message="format of ", category=UserWarning)
        generate(
            json.dumps(document, indent=2, sort_keys=True),
            input_file_type=InputFileType.JsonSchema,
            input_filename="bundle.json",
            output=destination,
            output_model_type=DataModelType.PydanticV2BaseModel,
            target_python_version=PythonVersion.PY_310,
            use_union_operator=True,
            use_standard_collections=True,
            enum_field_as_literal=LiteralType.All,
            snake_case_field=True,
            disable_timestamp=True,
            use_schema_description=True,
            use_field_description=True,
            use_double_quotes=True,
            field_constraints=True,
            # Defaults as `Field(default, ...)` rather than a raw JSON value assigned
            # beside `Annotated[...]`, which no type checker can hold to the field's type.
            use_annotated=False,
            class_name=class_name,
            custom_file_header=HEADER,
            collapse_root_models=True,
            formatters=[Formatter.BUILTIN],
        )
    destination.write_text(typeable(destination.read_text(encoding="utf-8")), encoding="utf-8")


# datamodel-code-generator spells a `propertyNames` pattern as a `constr(...)` dict key.
CONSTR = re.compile(r'constr\((pattern=r?"(?:[^"\\]|\\.)*")\)')
FUTURE = "from __future__ import annotations\n"


def typeable(source: str) -> str:
    """`source` with every `constr(pattern=...)` spelled as the type it returns.

    A call is not a type expression, so a checker refuses `dict[constr(...), V]`;
    pydantic's `constr(pattern=p)` is exactly `Annotated[str, StringConstraints(pattern=p)]`,
    which is one. The imports it needs are added, and the formatting pass sorts them.
    """
    rewritten, count = CONSTR.subn(r"Annotated[str, StringConstraints(\1)]", source)
    if count == 0:
        return source
    imports = "\nfrom typing import Annotated\n\nfrom pydantic import StringConstraints\n"
    return rewritten.replace(FUTURE, FUTURE + imports, 1)


def models_module(entries: list[tuple[str, str, str]]) -> str:
    """`onemessagebus.models`: every message's model under its family's name.

    `agent.planner-surface@1` is `PlannerSurfaceV1`, and `PlannerSurface` is the
    latest version of that family the registry holds. Two families that would
    share a name fail here rather than shadow one another. Every name is an
    explicit import or assignment listed in `__all__`.
    """
    families: dict[str, list[tuple[int, str, str, str]]] = {}
    for schema_id, module, class_name in entries:
        family, version = schema_id.rsplit("@", 1)
        public = pascal(family.split(".", 1)[1])
        families.setdefault(public, []).append((int(version), family, module, class_name))
    imports: list[str] = []
    latest: list[str] = []
    exported: list[str] = []
    for public in sorted(families):
        versions = sorted(families[public])
        named_families = sorted({family for _, family, _, _ in versions})
        if len(named_families) != 1:
            raise RuntimeError(f"{public} would name more than one family: {named_families}")
        for version, _, module, class_name in versions:
            imports.append(
                f"from ._generated.messages.{module} import {class_name} as {public}V{version}"
            )
            exported.append(f"{public}V{version}")
        latest.append(f"{public} = {public}V{versions[-1][0]}")
        exported.append(public)
    names = "".join(f'    "{name}",\n' for name in exported)
    return (
        f'{HEADER}\n"""The generated model of every message the registry holds, by its family\'s '
        "name.\n\n`PlannerSurface` is `agent.planner-surface@1`'s model at the latest version "
        "the registry\nholds, and `PlannerSurfaceV1` names that version; `messages.MESSAGES` "
        'maps each id\nto its model.\n"""\n\n'
        + "\n".join(imports)
        + "\n\n"
        + "\n".join(latest)
        + f"\n\n__all__ = [\n{names}]\n"
    )


def generated_files(bundle: dict[str, Any]) -> dict[str, bytes]:
    """Every file the generator owns, by its path below the package, formatted as the gate formats.

    That is all of `_generated/`, and the public `models.py` re-exporting its models.
    """
    with tempfile.TemporaryDirectory(prefix="onemessagebus-generate-") as scratch:
        package = Path(scratch)
        out = package / "_generated"
        (out / "messages").mkdir(parents=True)
        (out / "__init__.py").write_text(
            f'{HEADER}\n"""The Rust-owned contract, rendered for Python."""\n', encoding="utf-8"
        )
        render(contract_document(bundle), None, out / "contract.py")
        entries = []
        for schema_id in sorted(bundle["messages"]):
            document = named(bundle["messages"][schema_id])
            module = module_for(schema_id)
            class_name = pascal(document.get("title", module))
            render(document, class_name, out / "messages" / f"{module}.py")
            entries.append((schema_id, module, class_name))
        imports = "\n".join(f"from . import {module}" for _, module, _ in entries)
        mapping = "\n".join(f'    "{sid}": {module}.{name},' for sid, module, name in entries)
        (out / "messages" / "__init__.py").write_text(
            f'{HEADER}\n"""Every message the registry holds, by id."""\n\n'
            f"from pydantic import BaseModel\n\n{imports}\n\n"
            f"MESSAGES: dict[str, type[BaseModel]] = {{\n{mapping}\n}}\n",
            encoding="utf-8",
        )
        (package / "models.py").write_text(models_module(entries), encoding="utf-8")
        (out / "capabilities.json").write_text(
            json.dumps(bundle["capabilities"], indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        config = str(PACKAGE / "pyproject.toml")
        for command in (
            ["check", "--fix", "--select", "I,F401,UP,RUF022", "--quiet", "--config", config],
            ["format", "--quiet", "--config", config],
        ):
            subprocess.run([sys.executable, "-m", "ruff", *command, scratch], check=True)
        return owned_files(package)


def owned_files(package: Path) -> dict[str, bytes]:
    """What `package` holds of the generator's: all of `_generated/`, and `models.py`."""
    paths = [*sorted((package / "_generated").rglob("*")), package / "models.py"]
    return {
        path.relative_to(package).as_posix(): path.read_bytes()
        for path in paths
        if path.is_file() and "__pycache__" not in path.parts
    }


def diff(name: str, committed: bytes | None, fresh: bytes | None) -> str:
    """A unified diff of one file, committed against generated."""
    return "".join(
        difflib.unified_diff(
            (committed or b"").decode("utf-8").splitlines(keepends=True),
            (fresh or b"").decode("utf-8").splitlines(keepends=True),
            fromfile=f"{name} (committed)" if committed is not None else "/dev/null",
            tofile=f"{name} (generated)" if fresh is not None else "/dev/null",
        )
    )


def main(argv: list[str] | None = None) -> int:
    """Write the generated files, or report their drift under --check."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift; write nothing")
    parser.add_argument("--output", type=Path, default=OUTPUT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    fresh = generated_files(read_bundle())
    committed = owned_files(args.output)
    stale = sorted(
        name for name in fresh.keys() | committed.keys() if fresh.get(name) != committed.get(name)
    )
    if args.check:
        if not stale:
            return 0
        for name in stale:
            sys.stdout.write(diff(name, committed.get(name), fresh.get(name)))
        print(
            f"\ngenerate.py: {len(stale)} generated file(s) differ from the Rust bundle; "
            f"run the generator: {RERUN}",
            file=sys.stderr,
        )
        return 1
    for name in stale:
        target = args.output / name
        if name not in fresh:
            target.unlink()
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(fresh[name])
    for directory in sorted((args.output / "_generated").rglob("__pycache__")):
        shutil.rmtree(directory)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
