"""Every capability through the client against the real binary, over both transports.

Each verb is driven the way a user drives it — its happy path, and a refusal
that lands on the typed error for its exit code, in the binary's own words.
`ask`, `subscribe` and message types have journeys of their own beside this one.
"""

from __future__ import annotations

import asyncio
import contextlib
import fcntl
import json
import time
from collections.abc import Iterator
from pathlib import Path
from typing import Literal, cast

import pytest

from onemessagebus import (
    BusFailed,
    BusRefused,
    Client,
    Envelope,
    ValidatedPass,
    ValidatedRefuse,
    ValidatedUnjudged,
)
from tests.conftest import bus_config, make_transport

GREETING = {
    "title": "Greeting",
    "type": "object",
    "properties": {"text": {"type": "string"}},
    "required": ["text"],
    "additionalProperties": False,
}
SURFACE = {"kind": "finding", "message": "the base moved", "source": "proposal", "blocking": False}


async def test_the_schema_verbs(client: Client, scratch: Path) -> None:
    document = scratch / "greeting.json"
    document.write_text(json.dumps(GREETING), encoding="utf-8")
    assert await client.schema_register("demo.salute@1", document) == ""
    other = scratch / "other.json"
    other.write_text('{"title": "Other", "type": "object"}', encoding="utf-8")
    with pytest.raises(BusRefused) as held:
        await client.schema_register("demo.salute@1", other)
    assert held.value.message == (
        "demo.salute@1 is already registered with a different document; "
        "register a new version instead"
    )

    entries = {entry.id: entry for entry in await client.schema_list()}
    assert (entries["demo.salute@1"].family, entries["demo.salute@1"].version) == (
        "demo.salute",
        1,
    )
    assert "bus.resident-protocol@1" in entries
    assert "demo.salute@1" in (await client.schema_list(format="text")).splitlines()
    with pytest.raises(BusRefused, match="not a directory"):
        await client.schema_list(registry=document)

    assert await client.schema_check("demo.salute@1", {"text": "hi"}) == ""
    payload = scratch / "payload.json"
    payload.write_text('{"text": 7}', encoding="utf-8")
    with pytest.raises(BusFailed) as violated:
        await client.schema_check("demo.salute@1", file=payload)
    assert violated.value.exit == 1
    assert violated.value.message.startswith("demo.salute@1: at /text")
    with pytest.raises(BusRefused, match='"-x" is not a schema id'):
        await client.schema_check("-x", {})

    assert json.loads(await client.schema_gen("demo.salute@1", "json")) == GREETING
    assert "pub struct Greeting" in await client.schema_gen("demo.salute@1", "rust")
    with pytest.raises(BusRefused, match="generated by the python SDK package"):
        await client.schema_gen("demo.salute@1", "python")


async def test_the_events_verbs(client: Client, scratch: Path) -> None:
    stream = scratch / "events.jsonl"
    first = await client.events_emit(
        stream, "change-merged", "s1", {"branch": "main"}, labels={"run_id": "R", "round": 2}
    )
    assert isinstance(first, Envelope)
    assert (first.seq, first.kind, first.source, first.payload) == (
        1,
        "change-merged",
        "pipeline",
        {"branch": "main"},
    )
    assert first.labels is not None
    assert (first.labels.run_id, first.labels.round) == ("R", 2)
    payload = scratch / "payload.json"
    payload.write_text('{"branch": "next"}', encoding="utf-8")
    text = await client.events_emit(
        stream, "change-merged", "s1", file=payload, source="vcs", format="text"
    )
    assert " vcs change-merged stream=s1 seq=2 " in text

    merged = await client.events_merge([stream])
    assert [(envelope.seq, envelope.source) for envelope in merged] == [(1, "pipeline"), (2, "vcs")]
    assert len((await client.events_merge([stream], format="text")).splitlines()) == 2
    only_vcs = await client.events_merge([stream], filter={"include": [{"run_id": "R"}]})
    assert [envelope.seq for envelope in only_vcs] == [1]
    with pytest.raises(BusRefused, match="the event filter is unusable"):
        await client.events_merge([stream], filter={"nope": 1})

    # Another profile's envelopes are documents: the models are the agent vocabulary's.
    opened = await client.events_emit(
        scratch / "open.jsonl", "noted", "s2", {"a": 1}, profile="open", source="anything"
    )
    assert opened["source"] == "anything"
    read = await client.events_merge([scratch / "open.jsonl"], profile="open")
    assert read[0]["payload"] == {"a": 1}
    with pytest.raises(BusRefused, match="`Bad_Kind` is not kebab-case"):
        await client.events_emit(stream, "Bad_Kind", "s1", {})


@contextlib.contextmanager
def bound_spool(directory: Path) -> Iterator[None]:
    """A receiver bound to a spool, as `docs/inbox.md` lays one out: its document and its lock."""
    directory.mkdir()
    (directory / "spool.json").write_text(
        '{"schema_version": 1, "schema": "agent.note@1"}', encoding="utf-8"
    )
    with (directory / "receiver.lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        yield


def answer_one(directory: Path, disposition: object) -> None:
    """Take the one offer that arrives and answer it, the courier's renames and all."""
    deadline = time.monotonic() + 30
    while not (offers := sorted(directory.glob("*.offer.json"))):
        if time.monotonic() > deadline:
            raise AssertionError(f"no offer reached {directory}")
        time.sleep(0.02)
    offer = offers[0]
    message_id = offer.name.removesuffix(".offer.json")
    offer.rename(directory / f"{message_id}.taken.json")
    staging = directory / f"{message_id}.answer.json.staging"
    answer = {"schema_version": 1, "answer": {"disposition": disposition}}
    staging.write_text(json.dumps(answer), encoding="utf-8")
    staging.rename(directory / f"{message_id}.answer.json")


async def test_the_inbox_verbs(client: Client, scratch: Path) -> None:
    spool = scratch / "spool"
    note = {"addressee": "worker", "text": "look again at the migration"}
    with bound_spool(spool):
        answering = asyncio.ensure_future(
            asyncio.to_thread(answer_one, spool, {"interrupted": {"party": "worker"}})
        )
        disposition = await client.deliver(spool, note, wait=30)
        await answering
    assert disposition == {"interrupted": {"party": "worker"}}
    with pytest.raises(BusRefused):
        await client.deliver(scratch / "no-such-spool", message=note, wait=1)

    store = scratch / "carried.jsonl"
    store.write_text(
        '{"schema_version": 1, "kind": "onemessagebus-carry-store"}\n'
        + json.dumps({"ts": "2026-09-13T00:00:00.000Z", "schema": "agent.note@1", "message": note})
        + "\n",
        encoding="utf-8",
    )
    carried = await client.inbox_carried(store)
    assert [(entry.schema_, entry.message) for entry in carried] == [("agent.note@1", note)]
    assert "agent.note@1" in await client.inbox_carried(store, format="text")
    with pytest.raises(BusRefused, match="is not a carry store"):
        await client.inbox_carried(scratch / "no-such-store")


async def test_the_queue_verbs(client: Client, scratch: Path) -> None:
    kinds = await client.transports()
    assert [(kind.kind, kind.origin) for kind in kinds][:2] == [
        ("local", "builtin"),
        ("memory", "builtin"),
    ]
    assert (await client.transports(format="text")).startswith("local builtin")
    bogus = cast(Literal["json"], "bogus")  # sound: an out-of-domain format is the input under test
    with pytest.raises(BusRefused, match="invalid value 'bogus'"):
        await client.transports(format=bogus)

    sent = await client.send("surfaces", SURFACE)
    assert [(record.queue, record.id) for record in sent] == [("surfaces", 0)]
    record = scratch / "surface.json"
    record.write_text(json.dumps(SURFACE), encoding="utf-8")
    assert (await client.send("surfaces", None, file=record))[0].id == 1
    with pytest.raises(BusRefused, match="`nosuch` is not a queue this configuration declares"):
        await client.send("nosuch", SURFACE)

    [surfaces] = await client.status("surfaces")
    assert (surfaces.queue, surfaces.records) == ("surfaces", 2)
    every = {status.queue for status in await client.status()}
    assert {"surfaces", "replies", "commands", "command-outcomes", "greetings"} <= every
    assert (await client.status("surfaces", format="text")).startswith("surfaces records=2")
    with pytest.raises(BusRefused, match="`nosuch` is not a queue"):
        await client.status("nosuch")

    assert isinstance(await client.validate("surfaces", SURFACE), ValidatedPass)
    with pytest.raises(BusRefused, match="`nosuch` is not a queue"):
        await client.validate("nosuch", SURFACE)

    claimed = await client.next("surfaces")
    assert claimed is not None
    assert (claimed.queue, claimed.record["message"]) == ("surfaces", "the base moved")
    text = await client.next("surfaces", format="text")
    assert text is not None
    assert text.startswith("surfaces ")
    assert await client.next("surfaces") is None
    assert await client.next("surfaces", format="text") is None
    with pytest.raises(BusRefused, match="--asker is set to a blank value"):
        await client.next("surfaces", asker=" ")

    verdict = {"version": 3, "completion": True, "reason": "main"}
    with pytest.raises(BusFailed, match="no pending ask carries the correlation c-unknown"):
        await client.reply("surfaces", "c-unknown", verdict)
    with pytest.raises(BusRefused, match="declares no queue its replies"):
        await client.reply("greetings", None, {})

    assert await client.serve("surfaces", "onejudge", []) == []
    with pytest.raises(BusRefused, match="`nope` is not a codec this build links"):
        await client.serve("surfaces", "nope", [])


async def test_validate_answers_a_refusal_verdict_as_data(
    binary: Path, tmp_path_factory: pytest.TempPathFactory, transport_kind: str
) -> None:
    scratch = tmp_path_factory.mktemp("judged")
    (scratch / "onemessagebus.yaml").write_text(
        "version: 1\n"
        f"transport: {{kind: local, dir: {scratch / 'channel'}}}\n"
        "profile: planner-channel\n"
        "validators:\n"
        "  - {on: surfaces, when: {field: message, equals: loud}, kind: command,"
        " command: [sh, -c, 'echo too loud >&2; exit 1']}\n"
        "  - {on: surfaces, when: {field: message, equals: odd}, kind: command,"
        " command: [sh, -c, 'echo cannot say >&2; exit 3']}\n",
        encoding="utf-8",
    )
    async with Client(
        bus_config(binary, scratch), make_transport(transport_kind, scratch)
    ) as client:
        refused = await client.validate("surfaces", {**SURFACE, "message": "loud"})
        assert isinstance(refused, ValidatedRefuse)
        assert (refused.queue, refused.reason) == ("surfaces", "too loud\n")
        unjudged = await client.validate("surfaces", {**SURFACE, "message": "odd"})
        assert isinstance(unjudged, ValidatedUnjudged)
        assert "cannot say" in unjudged.reason
        assert isinstance(await client.validate("surfaces", SURFACE), ValidatedPass)
        with pytest.raises(BusFailed, match="too loud"):
            await client.send("surfaces", {**SURFACE, "message": "loud"})
        assert (await client.status("surfaces"))[0].records == 0
