#!/usr/bin/env node
// docs/sdk-parity.md, generated from the capability manifest and the clients.
//
// Every row is a statement about code that exists: what is declared comes from
// the bundle (`onemessagebus::CAPABILITIES`), and what each language implements
// comes from its client's own source, read the way scripts/sdk-coverage.mjs reads
// it. `--check` fails when the committed document is not what this would write.
//
// Usage: node scripts/parity-audit.mjs [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { ROOT, schemaBundle } from "./sdk-bundle.mjs";
import { CLIENTS, definedMethods, pythonName } from "./sdk-coverage.mjs";

const OUTPUT = "docs/sdk-parity.md";

const code = (text) => `\`${text}\``;
const cell = (text) => String(text).replaceAll("|", "\\|").replaceAll("\n", " ");

/** The document for `capabilities`, with each client's defined methods beside them. */
export function render(capabilities, typescript, python) {
  const out = [];
  const line = (text = "") => out.push(text);
  line("# SDK parity");
  line();
  line(
    "<!-- Generated by `just parity-audit` (scripts/parity-audit.mjs). Do not edit by hand. -->",
  );
  line();
  line(
    "Every capability of the `onemessagebus` binary, and how each consumer surface reaches it: the Rust library entry, the TypeScript and Python client methods, and the resident core's verb. The declared side is `onemessagebus::CAPABILITIES`, as the SDK bundle carries it; the implemented side is read from `npm/onemessagebus-sdk/src/client.ts` and `python/onemessagebus-sdk/src/onemessagebus/_client.py`, so a `yes` below is a method that exists.",
  );
  line();
  line("## How the parity is held");
  line();
  line(
    "- `crates/onemessagebus-cli/tests/capability.rs` walks the clap tree: every verb is a capability, and every flag is bound to an SDK option or declared uncovered with a reason.",
  );
  line(
    "- `crates/onemessagebus-cli/tests/library_surface.rs` exercises every capability's Rust library entry.",
  );
  line(
    "- `scripts/sdk-coverage.mjs` fails when either client lacks a method for a capability, or has a method no capability names; `crates/onemessagebus-e2e/tests/cross_language.rs` shows it going red when one is removed and green when restored.",
  );
  line(
    "- The resident core's verb set is the manifest itself: a request names a capability's method, and `crates/onemessagebus-e2e/tests/e2e/resident.rs` drives every one of them over the socket.",
  );
  line(
    "- Each SDK's generate-check fails when its generated contract — the manifest the argv builders read included — differs from a fresh generation from the bundle.",
  );
  line();
  line("## Capabilities");
  line();
  line("| Capability | Verb | Output | Rust library entry | TypeScript | Python | Resident |");
  line("| --- | --- | --- | --- | --- | --- | --- |");
  for (const capability of capabilities) {
    const py = pythonName(capability.method);
    const output = capability.output
      ? `${capability.stdout} ${code(capability.output)}`
      : capability.stdout;
    line(
      `| ${code(capability.method)} | ${code(`onemessagebus ${capability.verb.join(" ")}`)} | ${output} | ${code(capability.library_entry)} | ${typescript.has(capability.method) ? `yes, ${code(capability.method)}` : "**missing**"} | ${python.has(py) ? `yes, ${code(py)}` : "**missing**"} | yes, ${code(capability.method)} |`,
    );
  }
  line();
  line("## Options, flag by flag");
  line();
  line(
    "Each option is spelled camelCase in TypeScript and in a resident request's `args`, and snake_case in Python; each renders the flag beside it. A flag no option renders is listed with the reason it is not one.",
  );
  for (const capability of capabilities) {
    line();
    line(`### ${code(capability.method)} — ${code(`onemessagebus ${capability.verb.join(" ")}`)}`);
    line();
    const stdin = capability.stdin
      ? "a payload on stdin (a resident request's `input`)"
      : "no payload";
    line(`Options root ${code(capability.options ?? "none")}; takes ${stdin}.`);
    line();
    line("| Option | Python | Flag | Kind |");
    line("| --- | --- | --- | --- |");
    for (const binding of capability.bindings) {
      line(
        `| ${code(binding.option)} | ${code(pythonName(binding.option))} | ${binding.flag ? code(binding.flag) : "positional"} | ${binding.kind} |`,
      );
    }
    for (const uncovered of capability.uncovered) {
      line();
      line(`- ${code(uncovered.flag)} is not an SDK option: ${cell(uncovered.reason)}.`);
    }
  }
  line();
  return out.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const { capabilities } = schemaBundle({ script: "parity-audit", rerun: "just parity-audit" });
  let text;
  try {
    text = render(
      capabilities,
      definedMethods("typescript", CLIENTS.typescript),
      definedMethods("python", CLIENTS.python),
    );
  } catch (error) {
    console.error(`parity-audit: ${error.message}`);
    process.exit(1);
  }
  const path = resolve(ROOT, OUTPUT);
  if (!check) {
    writeFileSync(path, text);
    return;
  }
  let committed = "";
  try {
    committed = readFileSync(path, "utf8");
  } catch {
    // A missing document is a stale one.
  }
  if (committed !== text) {
    console.error(
      `parity-audit: ${OUTPUT} is not what the manifest and the clients say today; run \`just parity-audit\` and commit the result`,
    );
    process.exit(1);
  }
  console.log(`parity-audit: ${OUTPUT} is current`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) main();
